### PR TITLE
[TIMOB-23225] Fix: wrong size for child view with Ti.UI.SIZE

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-23225](https://jira.appcelerator.org/browse/TIMOB-23225)

```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green' });

var view = Ti.UI.createView({
    height: Ti.UI.SIZE,
    width: Ti.UI.SIZE,
    backgroundColor: 'orange'
});

var img1 = Ti.UI.createView({
    height: 100, width: Ti.UI.FILL,
    backgroundColor:'gray'
});
var img2 = Ti.UI.createView({
    height: 50, width: 50,
    top: 0, right: 0,
    backgroundColor: 'red'
});

view.add(img1);
view.add(img2);
win.add(view);

win.open();
```

timob-23225

### CODE REVIEW

**Comment by infosia** [comment]
build win 10

**Comment by sgtcoolguy** [comment]
build win 10

**Comment by sgtcoolguy** [comment]
build win 8.1

**Comment by sgtcoolguy** [comment]
build win 10

**Comment by sgtcoolguy** [comment]
build win 8.1

**Comment by infosia** [comment]
build win 10

**Pull request merged**
