### PR TITLE
[TIMOB-23931] Stop enumerating parent & children for View

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-23931](https://jira.appcelerator.org/browse/TIMOB-23931)

`Ti.UI.View` and its subclasses has `parent` and `children` property, and they are enumerable. That makes it impossible to log them through `JSON.stringify` because of circular references. We can easily workaround it by configuring them non-enumerable.

```
var win = Ti.UI.createWindow(),
    label = Ti.UI.createLabel();

win.addEventListener('open', function () {
    Ti.API.info(JSON.stringify(win,null,2));
});

win.add(label);
win.open();
```

### CODE REVIEW

**Comment by garymathews** [comment]
I receive a `nullptr` error when running the test case

```
Unhandled exception thrown: read access violation.
this->layoutDelegate__._Ptr was nullptr.
```
`L757 in TitaniumKit View.cpp`

**Comment by infosia** [comment]
`nullptr` in `this->layoutDelegate__` should be fixed in #888, so let's merge this PR after #888 is pushed to the master.

**Comment by infosia** [comment]
Should be ready for merge.

**Comment by garymathews** [comment]
CR: **PASS**
FT: **PASS**

👍

**Pull request merged**
