### PR TITLE
[TIMOB-25463] wrong event.source returned for View

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-25463](https://jira.appcelerator.org/browse/TIMOB-25463)

It turns out this issue is not specific to Alloy but classic app too.

```js
﻿var win = Ti.UI.createWindow({
    backgroundColor: 'green',
});

var tab1 = Ti.UI.createView({
    backgroundColor: 'white',
    top: 0, left: 0,
    width: Ti.UI.FILL,
    height: 40,
    id: 'tab1'
});

var more1 = Ti.UI.createView({
    backgroundColor: 'red',
    width: 100,
    height: Ti.UI.FILL,
    left: 0,
    id: 'more1'
});

var nested1 = Ti.UI.createView({
    backgroundColor: 'black',
    width: 10,
    height: 10,
    id: 'nested1'
});

var tab2 = Ti.UI.createView({
    backgroundColor: 'white',
    top: 100, left: 0,
    width: Ti.UI.FILL,
    height: 40,
    id: 'tab2'
});

var more2 = Ti.UI.createView({
    backgroundColor: 'blue',
    width: 100,
    height: Ti.UI.FILL,
    left: 0,
    id: 'more2'
});

var nested2 = Ti.UI.createView({
    backgroundColor: 'black',
    width: 10,
    height: 10,
    id: 'nested2'
});

var tab3 = Ti.UI.createView({
    backgroundColor: 'white',
    top: 200, left: 0,
    width: Ti.UI.FILL,
    height: 40,
    id: 'tab3'
});

var more3 = Ti.UI.createView({
    backgroundColor: 'yellow',
    width: 100,
    height: Ti.UI.FILL,
    id: 'more3'
});

var nested3 = Ti.UI.createView({
    backgroundColor: 'black',
    width: 10,
    height: 10,
    id: 'nested3'
});

var tab4 = Ti.UI.createView({
    backgroundColor: 'white',
    top: 300, left: 0,
    width: Ti.UI.FILL,
    height: 40,
    id: 'tab4'
});

var more4 = Ti.UI.createView({
    backgroundColor: 'pink',
    width: 100,
    height: Ti.UI.FILL,
    right: 0,
    id: 'more4'
});

var nested4 = Ti.UI.createView({
    backgroundColor: 'black',
    width: 10,
    height: 10,
    id: 'nested4'
});

function clicked(e) {
    alert(e.source.id);
}

win.addEventListener('click', clicked);

more1.add(nested1);
more2.add(nested2);
more3.add(nested3);
more4.add(nested4);
tab1.add(more1);
tab2.add(more2);
tab3.add(more3);
tab4.add(more4);
win.add(tab1);
win.add(tab2);
win.add(tab3);
win.add(tab4);
win.open();
```

Expected:

- Clicking red view should show "more1"
- Clicking black view inside red view should show "nested1"
- Clicking blue view should show "more2"
- Clicking black view inside blue view should show "nested2"
- Clicking yellow view should show "more3"
- Clicking black view inside yellow view should show "nested3"
- Clicking pink should show "more4"
- Clicking black view inside pink view should show "nested4"

### CODE REVIEW

**Comment by longton95** [comment]
@infosia I tried the fix with the customer's test case and its fixed for ws-local, but when I try it on the emulator only the id for the tab not the nested view.

**Comment by ssjsamir** [comment]
@infosia when I try the test case for this, i occasionally get "Undefined" hen clicking inside the views.

**Comment by infosia** [comment]
Hmm right, I got undefined occasionally too on my Windows 10 Mobile device... @ssjsamir Are you running on phone device/emulator too? For me this works well on my desktop machine as well as Windows 10 tablet device. I think we can merge this for now as long as it works on the desktop/tablet because of current usage of Windows 10 Mobile (as MS is obviously abandoning Win 10 Mobile). I'll raise new ticket for mobile separately then.

**Comment by ssjsamir** [comment]
@infosia Yes i was running on a windows 10 mobile device but on ws-local it seems to run fine. I'm in favour of merging as well if this is a mobile issue only and that we can create a new ticket.

**Comment by infosia** [comment]
Merged. Created [TIMOB-25542](https://jira.appcelerator.org/browse/TIMOB-25542) to track Win 10 Mobile issue.

**Pull request merged**
