### PR TITLE
[TIMOB-23164] Fix Windows 10 Store animate left and top test cases

### PR DESCRIPTION
**Pull request by garymathews**
- Use ``parent`` view to correctly determine the final animation positions for ``view``
- Add a timeout

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23164)

### CODE REVIEW

**Comment by garymathews** [comment]
The Windows 10 builds seem to stop at

```
[INFO] :   Started: address
```

**Comment by garymathews** [comment]
test this please

**Comment by garymathews** [comment]
test this please

**Comment by garymathews** [comment]
build win 8.1

**Comment by infosia** [comment]
👍

**Pull request merged**
