### PR TITLE
[TIMOB-23214] raulriera/XHR doesn't work

### PR DESCRIPTION
**Pull request by infosia**
Fix for [TIMOB-23214](https://jira.appcelerator.org/browse/TIMOB-23214)

[github.com/raulriera/XHR](https://github.com/raulriera/XHR)

```javascript
var win = Ti.UI.createWindow();
var XHR = require("xhr");
var xhr = new XHR();

var onSuccessCallback = function (e) {
    Ti.API.info('onSuccessCallback: ' + JSON.stringify(Object.keys(e)));
    win.backgroundColor = 'green';
};
var onErrorCallback = function (e) {
    Ti.API.info('onErrorCallback: ' + JSON.stringify(Object.keys(e)));
    win.backgroundColor = 'red';
};
win.addEventListener('open', function () {
    xhr.get("http://www.appcelerator.com/", onSuccessCallback, onErrorCallback);
});

win.open();
```

### CODE REVIEW

**Comment by infosia** [comment]
build win 10

**Comment by infosia** [comment]
Jenkins Windows 10 build failed due to:

> error MSB6003: The specified task executable "CL.exe" could not be run. There is not enough space on the disk.

**Comment by sgtcoolguy** [comment]
build win 10

**Comment by sgtcoolguy** [comment]
Can we add a unit test to our ti.network.httpclient suite? Looks like we failed before if you set Content-type header but had no content in the request (send call)?

If the build passes, I'll add that test and merge this with it...

**Comment by sgtcoolguy** [comment]
Manually merging.

**Pull request closed without merging**
