### PR TITLE
Implement missing Proxy properties & apiName

### PR DESCRIPTION
**Pull request by infosia**
I accidentally closed https://github.com/appcelerator/titanium_mobile_windows/pull/461. Pushed this again.

### CODE REVIEW

**Comment by infosia** [comment]
test this please

**Comment by sgtcoolguy** [comment]
@infosia  Looks good, but we still need to add the hard-coded api names to every other proxy too.

**Comment by infosia** [comment]
@sgtcoolguy Yes, I'm planning to do that in subsequent PR. Ticket: [TIMOB-19663](https://jira.appcelerator.org/browse/TIMOB-19663)

**Comment by infosia** [comment]
Hmm, [Jenkins passed this](http://studio-jenkins.appcelerator.org/job/titanium_mobile_windows_prs/1464/) actually, but github doesn't show them.

**Comment by infosia** [comment]
test this please

**Pull request merged**
