### PR TITLE
[TIMOB-23372] Fix Composite right and bottom margins

### PR DESCRIPTION
**Pull request by garymathews**
- Fix ``right`` and ``bottom`` margins in ``Composite`` ``Horizontal`` and ``Vertical`` of LayoutEngine
- The layout engine did not take into account the ``right`` offset when calculating the new width due to an incorrect ``if`` statement
- If a component is of width ``Ti.UI.SIZE`` and the ``right`` margin is specified, it should calculate the new width taking into account both ``left`` and ``right`` margins
- Made a workaround to match iOS and Android when percentage values of ``left`` and ``right`` are set inside a parent View

###### TEST CASE # 1
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'red' }),
    view = Ti.UI.createView({
        backgroundColor: 'orange',
        layout: "vertical",
        top: 10,
        left: 10,
        right: 10,
        height: Ti.UI.SIZE,
        width: Ti.UI.SIZE,
    }),
    label = Ti.UI.createLabel({
        left: 10,
        right: 10,
        color: "green",
        backgroundColor: 'yellow',
        text: "this is test text"
    }),
    button = Ti.UI.createButton({
        title: 'BUTTON',
        backgroundColor: 'green',
        left: 10,
        width: Ti.UI.SIZE
    });
view.add(label);
view.add(button);
win.add(view);
win.open();
```
###### TEST CASE # 2
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'red' }),
    a = Ti.UI.createView({
        backgroundColor: 'orange',
        top: 10,
        left: 10,
        right: 10,
        bottom: 10,
    }),
    b = Ti.UI.createView({
        backgroundColor: 'yellow',
        top: 10,
        left: 10,
        right: 10,
        bottom: 10,
    });
a.add(b);
win.add(a);
win.open();
```

###### TEST CASE # 3
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'red' }),
    label = Ti.UI.createLabel({
        left: 10,
        right: 10,
        backgroundColor:'yellow',
        color: "green",
        text: "this is test text"
    });
win.add(label);
win.open();
```

###### TEST CASE # 4
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green' }),
    view = Ti.UI.createView({
        backgroundColor: 'yellow',
        layout: "horizontal",
        top: 10,
        left: 10,
        right: 10,
        height: Ti.UI.SIZE,
        width: Ti.UI.SIZE
    }),
    label = Ti.UI.createLabel({
        left: 10,
        right: 10,
        color: "blue",
        text: "this is test text"
    });
view.add(label);
win.add(view);
win.open();
```

###### TEST CASE # 6
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'white' }),
    view = Ti.UI.createView({layout: "horizontal", top: 10, height: Ti.UI.SIZE, width: Ti.UI.SIZE});
    a = Ti.UI.createLabel({
        text: "A",
        height: 60,
        width: 60,
        color: "#C41230",
        borderRadius: 30,
        borderWidth: 2,
        borderColor: "#C41230",
        backgroundColor: "#F2D0D6",
        textAlign: "center",
        font: {
            fontSize: 20,
        },
        left: "10%"
    });
    b = Ti.UI.createLabel({
        text: "B",
        height: 60,
        width: 60,
        color: "#C41230",
        borderRadius: 30,
        borderWidth: 2,
        borderColor: "#C41230",
        backgroundColor: "#F2D0D6",
        textAlign: "center",
        font: {
            fontSize: 20,
        },
        left: "10%"
    });
    c = Ti.UI.createLabel({
        text: "C",
        height: 60,
        width: 60,
        color: "#C41230",
        borderRadius: 30,
        borderWidth: 2,
        borderColor: "#C41230",
        backgroundColor: "#F2D0D6",
        textAlign: "center",
        font: {
            fontSize: 20,
        },
        left: "10%"
    });
view.add(a);
view.add(b);
view.add(c);
win.add(view);
win.open();
```
[TIMOB-23372](https://jira.appcelerator.org/browse/TIMOB-23372)
[TIMOB-23377](https://jira.appcelerator.org/browse/TIMOB-23377)

### CODE REVIEW

**Comment by garymathews** [comment]
Fixes the layout issue in Corporate Directory

**Comment by infosia** [comment]
Layout in Corporate app goes pretty well, but for me following test code still doesn't work.  @garymathews Can you add some layout tests in `NMocha` (maybe in `ti.ui.layout.test`) so we can automate it?

```
var win = Ti.UI.createWindow({backgroundColor:'green'});
var view = Ti.UI.createView({
    backgroundColor: 'yellow',
    layout: "vertical",
    top: 10,
    left: 10,
    height: Ti.UI.SIZE,
    width: Ti.UI.SIZE,
});

var label = Ti.UI.createLabel({
    left: 10,
    right: 10,
    color: "blue",
    text: "this is test text"
});

view.add(label);

win.add(view);
win.open();
```

**Comment by garymathews** [comment]
@infosia Ooops that test case was wrong, it should have been this

```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green' }),
    view = Ti.UI.createView({
        backgroundColor: 'yellow',
        layout: "horizontal",
        top: 10,
        left: 10,
        right: 10,
        height: Ti.UI.SIZE,
        width: Ti.UI.SIZE
    }),
    label = Ti.UI.createLabel({
        left: 10,
        right: 10,
        color: "blue",
        text: "this is test text"
    });
view.add(label);
win.add(view);
win.open();
```

**Comment by garymathews** [comment]
@infosia I just tested your testcase on Android and Windows, and I get the same result

##### Android
Android

##### Windows
Windows

**Comment by infosia** [comment]
sigh this happens...we should take iOS as "reference platform" in this case.

**Comment by sgtcoolguy** [comment]
If you're seeing layout difference between platforms, take iOS as the "reference" platform and please open a JIRA ticket to make Android match for parity sake.

**Comment by garymathews** [comment]
I believe this is a bug with the vertical layout implementation of iOS and that Android and Windows are working correctly. [TIMOB-23385](https://jira.appcelerator.org/browse/TIMOB-23385)

**Comment by infosia** [comment]
ok, I think we want to merge this for now even when it has some parity issues that has been in question. @garymathews Can you merge latest changes from `master` to this branch and squash all commits you've made so we have less commits?

**Comment by infosia** [comment]
Thanks, I'm now reviewing this and writing some unit tests.

**Comment by garymathews** [comment]
build win 10

**Comment by infosia** [comment]
Note for reviewers: Please don't merge this yet.

**Comment by infosia** [comment]
Closing now, I've been updating/testing this in #709 .

**Pull request closed without merging**
