### PR TITLE
[TIMOB-23833] Always auto-generate capabilities

### PR DESCRIPTION
**Pull request by garymathews**
- Always include auto-generated capabilities, even if capabilities are already defined in `tiapp.xml`

##### app.js
```Javascript
Ti.App.setProximityDetection(true);
```
##### tiapp.xml
```XML
<windows>
    <manifest>
        <Capabilities>
            <Capability Name="internetClient" />
            <Capability Name="picturesLibrary" />
        </Capabilities>
    </manifest>
</windows>
```
```
appc run -p windows -S 10.0 --build-only
```

###### RESULT
```XML
<Capabilities>
    <Capability Name="internetClient" />
    <uap:Capability Name="picturesLibrary" />
    <DeviceCapability Name="proximity" />
</Capabilities>
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23833)

### CODE REVIEW

**Comment by garymathews** [comment]
Looks like there's some issues with the XML?

**Comment by garymathews** [comment]
Updated PR

**Comment by garymathews** [comment]
test this please

**Comment by garymathews** [comment]
It seems `travis-ci` is hanging?

**Comment by infosia** [comment]
Pushed restart the task: https://travis-ci.org/appcelerator/titanium_mobile_windows/builds/155850667

**Comment by infosia** [comment]
[travis-ci.org build](https://travis-ci.org/appcelerator/titanium_mobile_windows/builds/155850667) seems to be ok. Will review & merge this.

**Comment by infosia** [comment]
Looks good 👍

**Pull request merged**
