### PR TITLE
Fix module cmake config template

### PR DESCRIPTION
**Pull request by garymathews**
- Rename ```CustomModule_Config.cmake``` into ```{{moduleName}}_Config.cmake```
- Fixes module project CMake error

### CODE REVIEW

**Comment by infosia** [comment]
@garymathews Would you provide a command line or something to show how to reproduce the error?

**Comment by garymathews** [comment]
```ti create -t module -p windows```

**Comment by infosia** [comment]
@garymathews ok, I see some issues when you specify `name` option. I'm planning to use `moduleNameCamel` or `moduleIdAsIdentifier` for safer project name for cmake.

**Comment by infosia** [comment]
Closing, as taken over by #270

**Pull request closed without merging**
