### PR TITLE
[TIMOB-23657] borderRadius does not work for some components

### PR DESCRIPTION
**Pull request by garymathews**
- Fix ``borderRadius`` property for
  - ``Titanium.UI.Button``
  - ``Titanium.UI.ScrollView``
  - ``Titanium.UI.WebView``
  - ``Titanium.UI.TextField``
  - ``Titanium.UI.ScrollableView``
  - ``Titanium.UI.Switch``
  - ``Titanium.UI.TextArea``
  - ``Titanium.UI.SearchBar``
  - ``Titanium.UI.Slider``

###### TEST CASE
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'purple' }),
    scrollView = Ti.UI.createScrollView({
        layout: 'vertical',
        borderWidth: 5,
        borderColor: 'yellow',
        borderRadius: 5
    }),
    button = Ti.UI.createButton({
        backgroundColor: 'orange',
        title: 'BUTTON',
        borderWidth: 5,
        borderColor: 'yellow',
        borderRadius: 5
    }),
    webView = Ti.UI.createWebView({
        backgroundColor: 'orange',
        url: 'http://www.appcelerator.com/',
        borderWidth: 5,
        borderColor: 'yellow',
        borderRadius: 5
    }),
    textField = Ti.UI.createTextField({
        backgroundColor: 'orange',
        text: 'TEST TEXT',
        width: Ti.UI.FILL,
        borderWidth: 5,
        borderColor: 'yellow',
        borderRadius: 5
    }),
    scrollableView = Ti.UI.createScrollableView({
        backgroundColor: 'orange',
        width: Ti.UI.FILL,
        height: 70,
        borderWidth: 5,
        borderColor: 'yellow',
        borderRadius: 5
    }),
    toggle = Ti.UI.createSwitch({
        backgroundColor: 'orange',
        borderWidth: 5,
        borderColor: 'yellow',
        borderRadius: 5
    }),
    textArea = Ti.UI.createTextArea({
        backgroundColor: 'orange',
        borderWidth: 5,
        borderColor: 'yellow',
        borderRadius: 5
    }),
    searchBar = Ti.UI.createSearchBar({
        backgroundColor: 'orange',
        borderWidth: 5,
        borderColor: 'yellow',
        borderRadius: 5
    }),
    slider = Ti.UI.createSlider({
        backgroundColor: 'orange',
        borderWidth: 5,
        borderColor: 'yellow',
        borderRadius: 5,
        width: '50%'
    });

scrollView.add(button);
scrollView.add(webView);
scrollView.add(textField);
scrollView.add(scrollableView);
scrollView.add(toggle);
scrollView.add(textArea);
scrollView.add(searchBar);
scrollView.add(slider);

win.add(scrollView);
win.open();
```

###### NOTE
Components in the ticket that were not suitable to fix
  - ``Titanium.UI.PickerColumn``
  - ``Titanium.UI.ProgressBar``

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23657)

### CODE REVIEW

**Comment by garymathews** [comment]
build win 10

**Comment by garymathews** [comment]
build win 10

**Comment by infosia** [comment]
Why borderRadius for following components are considered "not suitable to fix"? Looks like iOS supports them.

  - ``Titanium.UI.ProgressBar``
  - ``Titanium.UI.SearchBar``
  - ``Titanium.UI.Slider``

**Comment by infosia** [comment]
For following components, looks good to me 👍 

  - ``Titanium.UI.Button``
  - ``Titanium.UI.ScrollView``
  - ``Titanium.UI.WebView``
  - ``Titanium.UI.TextField``
  - ``Titanium.UI.ScrollableView``
  - ``Titanium.UI.Switch``
  - ``Titanium.UI.TextArea``

**Comment by garymathews** [comment]
I've addressed the other components, however ``Titanium.UI.ProgressBar`` is made up of a ``StackPanel``, and for some reason ``Border`` does not work when set as the parent of the panel. We will have to find a workaround.

**Comment by infosia** [comment]
Added ticket for `ProgressBar.borderRadius` - [TIMOB-23682](https://jira.appcelerator.org/browse/TIMOB-23682)

**Comment by infosia** [comment]
Looks good, ok to merge once Jenkins passes it. (offline now?)

**Comment by infosia** [comment]
test this please

**Pull request merged**
