### PR TITLE
[TIMOB-23531] Fix: Tab title color is not changed on selection

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-23531](https://jira.appcelerator.org/browse/TIMOB-23531)

* Try to get "default color" from current theme if no Tab title color is specified.

```javascript
// create tab group
var tabGroup = Titanium.UI.createTabGroup();

//
// create base UI tab and root window
//
var win1 = Titanium.UI.createWindow({
    title: 'Tab 1',
    backgroundColor: '#fff'
});
var tab1 = Titanium.UI.createTab({
    title: 'Tab 1',
    window: win1,
    // titleColor: 'blue',
    // activeColor: 'orange'
});

var label1 = Titanium.UI.createLabel({
    color: '#999',
    text: 'I am Window 1',
    font: { fontSize: 20, fontFamily: 'Helvetica Neue' },
    textAlign: 'center',
    width: 'auto'
});

win1.add(label1);

//
// create controls tab and root window
//
var win2 = Titanium.UI.createWindow({
    title: 'Tab 2',
    backgroundColor: '#fff'
});
var tab2 = Titanium.UI.createTab({
    title: 'Tab 2',
    window: win2,
    // titleColor: 'blue',
    // activeColor: 'orange'
});

var label2 = Titanium.UI.createLabel({
    color: '#999',
    text: 'I am Window 2',
    font: { fontSize: 20, fontFamily: 'Helvetica Neue' },
    textAlign: 'center',
    width: 'auto'
});

win2.add(label2);

//
//  add tabs
//
tabGroup.addTab(tab1);
tabGroup.addTab(tab2);

// open tab group
tabGroup.open();
```

### CODE REVIEW

**Comment by garymathews** [comment]
test this please

**Comment by garymathews** [comment]
CR: **PASS**
FR: **PASS**

**Comment by garymathews** [comment]
build win 10

**Comment by garymathews** [comment]
build win 10

**Comment by infosia** [comment]
Hmm, Jenkins build is unstable now? I'm not sure what's happening there.

### TitaniumKit PR Build
```
LINK : fatal error LNK1105: cannot close file 'C:\Jenkins\workspace\TitaniumKit-prs\build\testing\examples\Debug\TitaniumKit_examples.lib' [C:\Jenkins\workspace\TitaniumKit-prs\build\testing\examples\TitaniumKit_examples.vcxproj]
```

### Windows 10 SDK PR Build

```
Error: Specified project does not exists: C:\ProgramData\Titanium\mobilesdk\win32\6.0.0.v20160621232034\node_modules\windowslib\wstool\wstool.csproj
```

**Comment by sgtcoolguy** [comment]
I'll take a look at the machines. Looks like a couple of them are acting up...

**Comment by sgtcoolguy** [comment]
Both Windows 10 build agents had Windows updates done and had hijacked the UI asking to schedule a restart. I'm restarting them now. The one that builds TitaniumKit isn't really responding... may be something more.

**Comment by infosia** [comment]
build win 10

**Pull request merged**
