### PR TITLE
[TIMOB-23261] Fix order of DeviceCapabilities in manifest

### PR DESCRIPTION
**Pull request by garymathews**
- Always declare ``DeviceCapability`` last [App capability declarations](https://msdn.microsoft.com/en-us/library/windows/apps/hh464936.aspx)

##### tiapp.xml
```XML
<windows>
  <manifest>
      <Capabilities>
          <Capability Name="internetClient"/>
         <DeviceCapability Name="location"/>
           <Capability Name="picturesLibrary" />
          <DeviceCapability Name="webcam" />
      </Capabilities>
  </manifest>
</windows>
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23261)

### CODE REVIEW

**Comment by infosia** [comment]
CR: **PASS**
FR: **PASS**

**Comment by infosia** [comment]
Just noticed that recent Ti CLI drops version version date string (.v2016xxx) from `6.0.0.v2016xxx` on `ti sdk install -b master -d`. maybe that's the reason why Jenkins failed for `test.js`?

```
05:36:13 Titanium SDK 6.0.0.v20160624160033 successfully installed!
05:36:14 C:\Jenkins\workspace\titanium_mobile_windows_10_prs\Tools\Scripts\build\test.js:77
05:36:14 		next(null, out['titanium'][selectedSDK]['path']);
```

**Comment by garymathews** [comment]
test this please

**Comment by garymathews** [comment]
build win 10

**Pull request merged**
