### PR TITLE
[TIMOB-17972] Implement Ti.UI.SearchBar

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-17972](https://jira.appcelerator.org/browse/TIMOB-17972)

## SearchBar with TableView
```javascript
var win = Ti.UI.createWindow({
    backgroundColor: 'green',
    layout:'vertical'
});

var searchBar = Ti.UI.createSearchBar({
    width: Ti.UI.FILL,
    height: '10%'
});

var sectionFruit = Ti.UI.createTableViewSection({ headerTitle: 'Fruit' });
sectionFruit.add(Ti.UI.createTableViewRow({ title: 'Apples' }));
sectionFruit.add(Ti.UI.createTableViewRow({ title: 'Bananas' }));

var sectionVeg = Ti.UI.createTableViewSection({ headerTitle: 'Vegetables' });
sectionVeg.add(Ti.UI.createTableViewRow({ title: 'Carrots' }));
sectionVeg.add(Ti.UI.createTableViewRow({ title: 'Potatoes' }));

var table = Ti.UI.createTableView({
    data: [sectionFruit, sectionVeg],
    search: searchBar,
    width: Ti.UI.FILL, height: '80%'
});

win.add(searchBar);
win.add(table);
win.open();
```

tableview

## SearchBar with ListView

```javascript
var win = Ti.UI.createWindow({
    backgroundColor: 'green',
    layout: 'vertical'
});
var searchBar = Ti.UI.createSearchBar({
    width: Ti.UI.FILL,
    height: '10%'
});
var listView = Ti.UI.createListView({
    searchView: searchBar,
    width: Ti.UI.FILL, height: '80%'
});
var sections = [];

var fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits' });
var fruitDataSet = [
    { properties: { title: 'Apple' } },
    { properties: { title: 'Banana' } },
];
fruitSection.setItems(fruitDataSet);
sections.push(fruitSection);

var vegSection = Ti.UI.createListSection({ headerTitle: 'Vegetables' });
var vegDataSet = [
    { properties: { title: 'Carrots' } },
    { properties: { title: 'Potatoes' } },
];
vegSection.setItems(vegDataSet);
sections.push(vegSection);

listView.sections = sections;
win.add(searchBar);
win.add(listView);
win.open();
```

listview1

listview

### CODE REVIEW

**Comment by infosia** [comment]
build win 10

**Comment by garymathews** [comment]
build win 10

**Comment by sgtcoolguy** [comment]
The HTTP client tests failed on win10, which happens intermittently I suppose. So we can ignore the failed build on Win 10 for now...

**Comment by sgtcoolguy** [comment]
@garymathews Can you please do an FR on this?

**Comment by garymathews** [comment]
FR: **PASS**
CR: **PASS**

**Pull request merged**
