### PR TITLE
[5_3_X] [TIMOB-23248] module cmake generator should use selected Visual Studio

### PR DESCRIPTION
**Pull request by infosia**
Cherry-pick #641 for 5_3_X

```
appc new -p windows -l trace --sdk 5.3.0.v2016xxxxx
cd xxx/windows
ti build -t ws-local -l trace --sdk 5.3.0.v2016xxxx -p windows
```

### CODE REVIEW

**Comment by infosia** [comment]
build win 10

**Comment by infosia** [comment]
build win 10

**Comment by garymathews** [comment]
Looks like these tests are failing again, although I've never been able to reproduce this myself
```
Windows10.Store.Titanium.UI.View.TIMOB-20598
Windows10.Store.Titanium.UI.View.animate (left)
Windows10.Store.Titanium.UI.View.animate (top)
```

**Comment by infosia** [comment]
Yeah, I don't know what's happens there...I'll disable them again :(

**Comment by infosia** [comment]
build win 10

**Pull request merged**
