### PR TITLE
TIMOB-18860 Introduce Nullable type into TitaniumKit

### PR DESCRIPTION
**Pull request by sgtcoolguy**
This just uses boost::optional for spot I needed it badly before: Ti.UI.Animation so we could tell if properties had specific values set by user or not.

https://jira.appcelerator.org/browse/TIMOB-18860

### CODE REVIEW

**Comment by infosia** [comment]
@sgtcoolguy Do you have a sample code or something that I can test to see if it works?

**Comment by sgtcoolguy** [comment]
@infosia I need to push an #include fix for travis, and then I'll also post the app.js I used to test.

**Comment by sgtcoolguy** [comment]
@infosia 
``` javascript
var win = Titanium.UI.createWindow({});

var view = Ti.UI.createView({
    top: 20,
    left: 10,
    width: 345,
    height: 600,
    backgroundColor: "red"
});

var imageView = Ti.UI.createImageView({
    opacity: 0.0,
    image: 'http://iconizer.net/files/IconSweets/orig/email.png'
});
view.add(imageView);
win.add(view);
win.open();

Ti.API.info('app.js running...');

Ti.API.info('animating opacity...');
imageView.animate({
    opacity: 1,
    autoreverse: true,
    repeat: 2,
    duration: 5000,
    delay: 2000
}, function () {
    Ti.API.info('Done with opacity animation.');
    view.animate({
        backgroundColor: 'blue',
        autoreverse: true,
        duration: 5000
    }, function () {
        Ti.API.info('Done with backgroundColor animation.');
        view.animate({
            top: 0,
            duration: 5000
        }, function () {
            Ti.API.info('Done with top animation.');
            view.animate({
                left: 0,
                duration: 5000
            }, function () {
                Ti.API.info('Done with left animation.');
            });
        });
    });
});

**Comment by sgtcoolguy** [comment]
test this please

**Pull request merged**
