### PR TITLE
[TIMOB-24422] Skip installing dependencies

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-24422](https://jira.appcelerator.org/browse/TIMOB-24422)

Skip installing app dependencies manually. WinAppDeployCmd should be taking care of that for now. I also added `--installDependencies` flag just to keep backward compatibility.

```
> appc run -p windows --target wp-emulator --wp-sdk 10.0 -l trace
```

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
So, I finally nailed this down to invalid windows Firewall rules as the cause. I had set up inbound TCP, but not UDP - which actually resulted in this error happening intermittently. Yuck.

**Comment by sgtcoolguy** [comment]
So, I've been looking at this issue occasionally (on build machines). I strongly suspect something is up with the new hyperloop stuff and the app dependencies/min version OS. From what I've found from Googling, some people have had similar issues that were magically fixed by bumping the min OS version in the AppPackage manifest xml file, which really related to the dependency libraries that got installed.
Additionally, if I install an app from VS 2015 onto the emulator first and keep it open and then build, it seems to work most of the time.
I think we're not installing some dependency library we should or something (I recall seeing a new .NET core dependency getting installed from a branch new universal app in VS2015 when I run it on the emulator)

**Comment by infosia** [comment]
Thanks for update. That sounds this error may be related to something I got while integrating Visual Studio 2017 #959 too.

**Comment by infosia** [comment]
I ended up finding a way to explicitly running Visual Studio IDE as a compiler (using [Devenv](https://msdn.microsoft.com/en-us/library/b20w810z.aspx)) behind the scenes and I hope this works for Jenkins dependency issue too. I will update this PR soon to see how it works on Jenkins.

**Comment by infosia** [comment]
So it turns out that `devenv` does not quite work well for this situation because it does not generate application packages (appx). I found interesting behavior while working on #959, that is *some batch tools (`.bat`) does not work well when it is executed by [8.3 filenames](https://en.wikipedia.org/wiki/8.3_filename). We are usually using 8.3 filename when requiring `vcvarsall.bat` but it seems it does not work correctly with 8.3 filename. I'm also guessing that maybe we should not use `vcvarsall.bat` but should use `VsDevCmd.bat` instead because it's the file that Visual Studio Developer Console is using. I was able to make it work locally with Visual Studio 2017 with long filename (I mean not 8.3 filename).

**Comment by infosia** [comment]
Closing, I am pushing #962 instead.

**Pull request closed without merging**
