### PR TITLE
[TIMOB-19125] Windows: console.debug is not implemented

### PR DESCRIPTION
**Pull request by FokkeZB**
https://jira.appcelerator.org/browse/TIMOB-19125

### CODE REVIEW

**Comment by infosia** [comment]
LGTM :+1:

**Comment by FokkeZB** [comment]
Achievement unlocked: wrote 1 line of C++ :wink:

**Comment by sgtcoolguy** [comment]
Does it count if the line was actually JS inside a string? :laughing:

**Comment by FokkeZB** [comment]
Ssssst!

**Pull request merged**
