### PR TITLE
[TIMOB-23621] Improve arguments error for function call

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-23621](https://jira.appcelerator.org/browse/TIMOB-23621)

```javascript
var win = Ti.UI.createWindow();
Ti.UI.createTableViewRow({ title: 'Bananas' });
var table = Ti.UI.createTableView({});
table.insertRowAfter(Ti.UI.createTableViewRow({ title: 'notEnoughArgs' }));
win.add(table);
win.open();
```

*Expected*

- Error message: `insertRowAfter: Invalid number of arguments. Expected 2 but got 1` is shown in the error message window
- Following messages are shown in the console

```
[ERROR] ----- Titanium Javascript Runtime Error -----
[ERROR] In app.js: 4,21
[ERROR] Message: Uncaught Error: insertRowAfter: Invalid number of arguments. Expected 2 but got 1
```

### CODE REVIEW

**Comment by infosia** [comment]
build win 10

**Comment by infosia** [comment]
test this please

**Comment by garymathews** [comment]
Nice! :+1:

A few `Geolocation` functions need updating?

```C++
TITANIUM_FUNCTION(GeolocationModule, forwardGeocoder)
{
	if (arguments.size() >= 2) {
		ENSURE_ARGUMENT_INDEX(1);
		ENSURE_STRING_AT_INDEX(address, 0);
		ENSURE_OBJECT_AT_INDEX(callback, 1);
		forwardGeocoder(address, callback);
	} else if (arguments.size() >= 1) {
		ENSURE_STRING_AT_INDEX(address, 0);
		forwardGeocoder(address, get_context().CreateObject());
	}
	return get_context().CreateUndefined();
}

...
```

**Comment by garymathews** [comment]
CR: **PASS**
FR: **PASS**

**Pull request merged**
