### PR TITLE
[TIMOB-24760] Implement scrollstart, scrolling, scrollend and marker event for ListView

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-24760](https://jira.appcelerator.org/browse/TIMOB-24760) + [TIMOB-24749](https://jira.appcelerator.org/browse/TIMOB-24749)

Implement ListView `scrollstart`, `scrolling`, `scrollend` and `marker` event

Here's a test case for  [ListView.marker](https://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.ListView-event-marker) event:

- `{ sectionIndex: 0, itemIndex: 1 }` marker event should be fired when ListView is loaded
- `{ sectionIndex: 5, itemIndex: 1 }` marker event should be fired when it is visible (when you scroll down the list)
- Each markers should fire `marker` event only once.

```js
var win = Ti.UI.createWindow({ backgroundColor: 'green', layout: 'vertical' });

var listView = Ti.UI.createListView({ width: Ti.UI.FILL, height: Ti.UI.FILL });
var sections = [];

for (var i = 0; i < 10; i++) {
    var fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits ' + i });
    var items = [];
    for (var j = 0; j < 3; j++) {
        items.push({ properties: { title: 'Apple ' + i + '.' + j } });
    }
    fruitSection.setItems(items);
    sections.push(fruitSection);
}

listView.sections = sections;

// This should be fired immediately after ListView data is loaded
listView.addMarker({ sectionIndex: 0, itemIndex: 1 });

// This should be fired when you scroll down the list
listView.addMarker({ sectionIndex: 5, itemIndex: 1 });

listView.addEventListener('marker', function (e) {
    Ti.API.info(JSON.stringify(listView.sections[e.sectionIndex].items[e.itemIndex].properties));
});

listView.addEventListener('scrollstart', function (e) {
    Ti.API.info('scrollstart');
});
listView.addEventListener('scrolling', function (e) {
    Ti.API.info('scrolling');
});
listView.addEventListener('scrollend', function (e) {
    Ti.API.info('scrollend');
});

listView.addEventListener('itemclick', function (evt) {
    var clickItemIndex = evt.itemIndex;
    var clickSectionIndex = evt.sectionIndex;

    alert('sectionCount=' + listView.sectionCount + ' section=' + clickSectionIndex + ' item=' + clickItemIndex + '\r\n' + listView.sections[clickSectionIndex].items[clickItemIndex].properties.title);
});

win.add(listView);
win.open();
```

### CODE REVIEW

**Comment by infosia** [comment]
So my implementation only does simply mapping `ListView->ViewChanged` with `scrollend` event, that's why because it is constantly fired when you scroll down the list. Maybe I could use touch-release events along with this to check if user really ends scrolling? I will look into it.

**Comment by infosia** [comment]
Now it's working much better than before by checking`IsIntermediate` state. On Windows mobile device it works as expected. On Windows desktop it works more natural when you drag (and move) vertical scroll bar. It still fires the events constantly when you click vertical arrow button in scroll view on Windows desktop, but I would think this is platform behavior because click event is constantly fired (click and release events) on the control.

Please review again @ewanharris

**Comment by ewanharris** [comment]
Changes look good working from VS, triggering a rebuild to try and get an SDK build

**Comment by ewanharris** [comment]
@infosia so checking the Jenkins logs there looks to be a legit issue caught by the unit tests. It's currently failing on [this test](https://github.com/appcelerator/titanium_mobile_windows/blob/2b8027771f6f8ec063f6b653c33ad113af2ac940/Examples/NMocha/src/Assets/ti.ui.searchbar.test.js#L33-L54), what it boils down to is a ListView being added to a Window with no sections, only on 8.1 it seems too

````js
var win = Ti.UI.createWindow();
var listview = Ti.UI.createListView({
        height: 600
});
var fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits ' });
//listview.sections = [fruitSection];
win.add(listview)
win.open();
````

**Comment by infosia** [comment]
@ewanharris This should be ready for now, please review.

**Comment by ewanharris** [comment]
LGTM! Good to merge once branch is updated


@infosia, just an fyi that I filed two tickets [TIMOB-24905](https://jira.appcelerator.org/browse/TIMOB-24905) regarding the scrolling event firing when user is not touching the screen (the way the docs read to me is at odds with the behaviour on Android and iOS), and [TIMOB-24904](https://jira.appcelerator.org/browse/TIMOB-24904), the aforementioned issue on 8.1, which only occurs on Windows Phone 8.1 emulators

Test environment:

Studio: 4.9.0.201705302345
Appc CLI: 6.2.2
Appc NPM: 4.2.9
Nokia Lumia 550
Windows 10 Mobile emulator 10.0.14393
Windows 10 Pro 10.0.15063

**Comment by ewanharris** [comment]
Investigated the test failure as it is common, https://jira.appcelerator.org/browse/TIMOB-24907. Will be pushing a possible fix for the test soon. Merging

**Pull request merged**
