### PR TITLE
[TIMOB-23402] Analytics: Add data element to JSON payload for windows phone parity

### PR DESCRIPTION
**Pull request by sgtcoolguy**
https://jira.appcelerator.org/browse/TIMOB-23402

### CODE REVIEW

**Comment by garymathews** [comment]
build win 10

**Comment by sgtcoolguy** [comment]
Github is having some issues, so I think the build machines are struggling to grab the commit to build...

**Comment by garymathews** [comment]
It seems to be working now!

**Comment by garymathews** [comment]
CR: **PASS**
FR: **PASS**

**Pull request merged**
