### PR TITLE
First working version of Windows 10 mobile emulator

### PR DESCRIPTION
**Pull request by sgtcoolguy**
Behaves a little oddly around prompting for cert still...

https://jira.appcelerator.org/browse/TIMOB-20097

Needs appcelerator/windowslib#28

### CODE REVIEW

**Comment by yuchi** [comment]
:tada:

**Comment by infosia** [comment]
@sgtcoolguy  How do I test this? I tried `ti build --platform windows --target wp-emulator --wpsdk 10.0` as well as `ti build --platform windows --target ws-local --wpsdk 10.0` but it doesn't give me a Windows 10 emulator on the list.

**Comment by sgtcoolguy** [comment]
That should work. I did ti build -p windows -C 10-0-1 --wp-sdk 10.0 -T wp-emulator


On Dec 14, 2015, at 9:11 PM, Kota Iguchi <notifications@github.com<mailto:notifications@github.com>> wrote:


@sgtcoolguy<https://github.com/sgtcoolguy> How do I test this? I tried ti build --platform windows --target wp-emulator --wpsdk 10.0 as well as ti build --platform windows --target ws-local --wpsdk 10.0 but it doesn't give me a Windows 10 emulator on the list.

-

**Comment by infosia** [comment]
oh I just noticed `ti sdk install -b master -d` doesn't grab latest sdk...it hasn't been updated for a while. maybe something to do with the error in Jenkins. I'll build it by myself, thanks.

http://builds.appcelerator.com.s3.amazonaws.com/index.html

**Pull request merged**
