### PR TITLE
[TIMOB-23343] Fix: Map annotations do not handle click events

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-23343](https://jira.appcelerator.org/browse/TIMOB-23343)

Supported properties:

- latitude
- longitude
- map
- clicksource (`pin` when annotation is clicked,`null` otherwise)
- annotation (only when annotation is clicked)
- title (only when annotation is clicked)
- subtitle (only when annotation is clicked)
- type, source

```javascript
var win = Titanium.UI.createWindow();

var mountainView = Titanium.Map.createAnnotation({
    latitude: 37.390749,
    longitude: -122.081651,
    title: "Previous Appcelerator HQ",
    subtitle: 'Mountain View, CA',
    pincolor: Titanium.Map.ANNOTATION_RED,
    myid: 1 // Custom property to uniquely identify this annotation.
});

var mapview = Titanium.Map.createView({
    mapType: Titanium.Map.STANDARD_TYPE,
    region: {
        latitude: 37.390749, longitude: -122.081651,
        latitudeDelta: 0.01, longitudeDelta: 0.01
    },
    annotations: [mountainView]
});

win.add(mapview);

mapview.addEventListener('click', function (evt) {
    if (evt.annotation) {
        Ti.API.info("Annotation " + evt.title + " clicked, id: " + evt.annotation.myid);
    }
    Ti.API.info(evt.longitude + " : " + evt.latitude);
});
win.open();
```

### CODE REVIEW

**Comment by garymathews** [comment]
I crash when I try to output the event as a JSON object

```Javascript
mapview.addEventListener('click', function (evt) {
    Ti.API.info(JSON.stringify(evt, null, ' '));
});
```

I think this is due to an attempt to access objects that don't exist such as ``rightView`` ``leftView`` ``customView`` in ``Titanium::Annotation``

```C++
TITANIUM_PROPERTY_GETTER(Annotation, rightView)
{
	return rightView->get_object(); // rightView may be empty
	...
	// add validation?
	const auto rightView = get_rightView();
	if (rightView) {
		return rightView->get_object();
	}
	return get_context().CreateNull();
}
```

**Comment by infosia** [comment]
@garymathews Nice catch! I've fixed the crash. Now `JSON.stringify(evt)` will throw JSON `circular structure` exception but it's an expected result. Ready for merge.

**Comment by infosia** [comment]
build win 10

**Comment by infosia** [comment]
build win 10

**Pull request merged**
