### PR TITLE
CMake  Windows 10 RTM Support - WIP

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-19651](https://jira.appcelerator.org/browse/TIMOB-19651)

Update to CMake 3.3.2 with Windows 10 Support

```
cmake -G "Visual Studio 14 2015" -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0 ...
```

### CODE REVIEW

**Comment by infosia** [comment]
@sgtcoolguy , could we install latest Windows Update to the Jenkins? maybe we need latest .NET framework too. The cmake failed to run immediately at build.js but I'm not sure why, I can't reproduce this on my end.

```
17:52:20 C:\Jenkins\workspace\titanium_mobile_windows_prs\Tools\Scripts\build>call node build.js 
17:52:20 Building WindowsPhone 8.1 x86: Release
17:52:21 [31mFailed to run CMake[39m
```

**Comment by sgtcoolguy** [comment]
Here's what I get when I run by double-clicking the binary from Explorer:
cmake_failed

**Comment by garymathews** [comment]
It's because the Jenkins build server needs [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

**Comment by sgtcoolguy** [comment]
@garymathews @infosia Yes, but I think we may be able to build a version of cmake against VS 2013 and use that binary to avoid needing to force the build server - and Windows 8.1/VS 2013 users - to install that extra dependency.

I'm trying to build that Win10 feature branch off the fork locally and see if that works.

**Comment by infosia** [comment]
test this please

**Comment by infosia** [comment]
test this please

**Pull request merged**
