### PR TITLE
[TIMOB-24761] Lightweight ListView for Windows

### PR DESCRIPTION
**Pull request by infosia**
DO NOT MERGE

[TIMOB-24761](https://jira.appcelerator.org/browse/TIMOB-24761)

Lightweight `Ti.UI.Windows.ListView` implementation that is aiming for better performance and more flexible layout & binding based on [XAML DataTemplate](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.datatemplate). `Ti.UI.Windows.ListView` acts like lightweight version of `Ti.UI.ListView` with limited functionalities, it borrows some API from `Ti.UI.ListView` so you can use `Ti.UI.ListSection` and `Ti.UI.ListItem` with it.

**Differences between `Ti.UI.ListView`**

Some properties are not supported. Use [XAML DataTemplate](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.datatemplate) in `Resource/ListViewItemTemplate.xaml` instead.

- `templates` property (ListView custom item template) is not supported. 
- `headerView`, `headerTitle`, `footerView` and `footerTitle` are not supported.

## ListView sections with header

```js
var win = Ti.UI.createWindow({ backgroundColor: 'green', layout: 'vertical' }),
    cmdView = Ti.UI.createView({
        width: Ti.UI.FILL,
        height: Ti.UI.SIZE,
        layout: 'horizontal',
        backgroundColor: 'gray'
    }),
    goSection0 = Ti.UI.createButton({
        title: 'Section 0'
    }),
    goSection1 = Ti.UI.createButton({
        title: 'Section 1'
    }),
    goSection2 = Ti.UI.createButton({
        title: 'Section 2'
    });

var items0 = [],
    items1 = [],
    items2 = [];

for (var i = 0; i < 20; i++) {
    items0.push({ properties: { title: 'Fruit ' + i, image: 'Square150x150Logo.png' } });
    items1.push({ properties: { title: 'Vegetable ' + i, image: 'Square150x150Logo.png' } });
    items2.push({ properties: { title: 'Meat ' + i, image: 'Square150x150Logo.png' } });
}

var fruitSection = Ti.UI.createListSection({
    headerTitle: 'Fruits',
    items: items0
}),
    vegSection = Ti.UI.createListSection({
        headerTitle: 'Vegetables',
        items: items1
    }),
    meatSecion = Ti.UI.createListSection({
        headerTitle: 'Meats',
        items: items2
    });

var listView = Ti.UI.Windows.createListView({
    width: Ti.UI.FILL,
    height: '80%',
    sections: [fruitSection, vegSection, meatSecion]
});

goSection0.addEventListener('click', function () {
    listView.scrollToItem(0, 0);
});
goSection1.addEventListener('click', function () {
    listView.scrollToItem(1, 0);
});
goSection2.addEventListener('click', function () {
    listView.scrollToItem(2, 0);
});

listView.addEventListener('itemclick', function (e) {
    alert(JSON.stringify(e.properties));
});

cmdView.add(goSection0);
cmdView.add(goSection1);
cmdView.add(goSection2);

win.add(cmdView);
win.add(listView);
win.open();
```

### Resource/ListViewItemTemplate.xaml

`defaultItemTemplate` is the template for ListView items. `defaultItemTemplateGroupStyle` is the template for section headers.

```xaml
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" 
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <DataTemplate x:Key="defaultItemTemplate">
        <Grid Height="60" Margin="6">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="Auto"/>
                <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
            <Border Background="{StaticResource ListViewItemPlaceholderBackgroundThemeBrush}" Width="54" Height="54">
                <Image Source="{Binding Image}" Stretch="UniformToFill"/>
            </Border>
            <StackPanel Grid.Column="1" VerticalAlignment="Top" Margin="10,0,0,0">
                <TextBlock Text="{Binding Title}" TextWrapping="NoWrap"/>
                <TextBlock Text="{Binding Subtitle}" TextWrapping="NoWrap"/>
                <TextBlock Text="{Binding Description}" MaxHeight="54"/>
            </StackPanel>
        </Grid>
    </DataTemplate>

    <GroupStyle x:Key="defaultItemTemplateGroupStyle">
        <GroupStyle.HeaderTemplate>
            <DataTemplate>
                <TextBlock
                    Text="{Binding Title}"
                    FontSize="40" />
            </DataTemplate>
        </GroupStyle.HeaderTemplate>
    </GroupStyle>

</ResourceDictionary>
```

## ListView without sections

```js
var win = Ti.UI.createWindow({ backgroundColor: 'green', layout: 'vertical' });

var items0 = [];
for (var i = 0; i < 50; i++) {
    items0.push({ properties: { title: 'Fruit ' + i, image: 'Square150x150Logo.png' } });
}

var listView = Ti.UI.Windows.createListView({
    width: Ti.UI.FILL,
    height: Ti.UI.FILL,
    sections: [Ti.UI.createListSection({items: items0})]
});

listView.addEventListener('itemclick', function (e) {
    alert(JSON.stringify(e.properties));
});

win.add(listView);
win.open();
```

### Resource/ListViewItemTemplate.xaml

Note that when you remove `defaultItemTemplateGroupStyle` from template, section header is not displayed.

```xml
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" 
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <DataTemplate x:Key="defaultItemTemplate">
        <Grid Height="60" Margin="6">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="Auto"/>
                <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
            <Border Background="{StaticResource ListViewItemPlaceholderBackgroundThemeBrush}" Width="54" Height="54">
                <Image Source="{Binding Image}" Stretch="UniformToFill"/>
            </Border>
            <StackPanel Grid.Column="1" VerticalAlignment="Top" Margin="10,0,0,0">
                <TextBlock Text="{Binding Title}" TextWrapping="NoWrap"/>
                <TextBlock Text="{Binding Subtitle}" TextWrapping="NoWrap"/>
                <TextBlock Text="{Binding Description}" MaxHeight="54"/>
            </StackPanel>
        </Grid>
    </DataTemplate>
    
</ResourceDictionary>
```

### CODE REVIEW

**Comment by garymathews** [comment]
I think this should be a separate module

**Comment by infosia** [comment]
@garymathews I think that's fair. Do we have any repositories that we can put this kind of extension module? [appcelerator-archive](https://github.com/appcelerator-archive) I guess?

**Comment by garymathews** [comment]
@infosia https://github.com/appcelerator-modules/

**Comment by infosia** [comment]
Will start from [appcelerator-modules/ti.xaml.listview](https://github.com/appcelerator-modules/ti.xaml.listview).

**Comment by infosia** [comment]
Closing, started from [appcelerator-modules/ti.xaml.listview](https://github.com/appcelerator-modules/ti.xaml.listview)

**Pull request closed without merging**
