### PR TITLE
[TIMOB-24856] Implement bubbleParent functionality

### PR DESCRIPTION
**Pull request by garymathews**
- Implement `Titanium.Proxy.bubbleParent` functionality

###### TEST CASE
- Clicking the purple button should not fire the `click` event when `bubbleParent` is `false`
- Clicking the blue view should still fire the `click` event
```JS
var win = Ti.UI.createWindow(),
    view_a = Ti.UI.createView({ width: 300, height: 300, backgroundColor: 'red' }),
    view_b = Ti.UI.createView({ width: 200, height: 200, backgroundColor: 'blue' }),
    btn = Ti.UI.createButton({ title: 'TEST' , backgroundColor: 'purple', bubbleParent: false}),
    cb = function (e) {
        alert('click: ' + JSON.stringify(e, null, 2));
    };

view_a.addEventListener('click', cb);
// view_a.removeEventListener('click', cb);

view_b.add(btn);
view_a.add(view_b);

win.add(view_a);
win.open();
```

##### NOTE: it looks like the _diff_ also includes code that hasn't really changed, making it hard to review. Mostly in `WindowsViewLayoutDelegate.cpp`

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24856)

### CODE REVIEW

**Comment by infosia** [comment]
@garymathews Is this ready for review? I usually mark *DO NOT MERGE* when it is not ready for review, but I'm just checking.

**Comment by garymathews** [comment]
@infosia there's a couple of things I need to change

**Comment by garymathews** [comment]
@infosia ready for review.

**Comment by infosia** [comment]
I'm going to take over this. @garymathews Let me know if you have something more to share on this.

**Pull request closed without merging**
