### PR TITLE
[TIMOB-24454] Improve library integration with module

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-24454](https://jira.appcelerator.org/browse/TIMOB-24454)

Package libraries just like what Titanium Android module does for use of 3rd party JARs. 

- Every \*.lib, \*.dll and \*.winmd files in *lib* folder will be packaged into module and also copied/linked during Ti app build.
- Every files in *platform* folder are packaged into module and copied into Ti app so module can overwrite files during Ti app build.

For steps to test and sample code, refer to [TIMOB-24454](https://jira.appcelerator.org/browse/TIMOB-24454)

### CODE REVIEW

**Comment by infosia** [comment]
@garymathews Nice catch! Updated.

**Comment by garymathews** [comment]
@infosia it seems I'm not getting the `winmd` references automatically when building.

```
[WARN]  C:\Users\gmathews\projects\winModule\windows\src\ComAppcModuleTest3.cpp(98): error C2653: 'SAP': is not a class or namespace name [C:\Users\gmathews\projects\winModule\windows\Windows10.ARM\ComAppcModuleTest3.vcxproj]
[WARN]  C:\Users\gmathews\projects\winModule\windows\src\ComAppcModuleTest3.cpp(98): error C2061: syntax error: identifier 'UsageInfo' [C:\Users\gmathews\projects\winModule\windows\Windows10.ARM\ComAppcModuleTest3.vcxproj]
C:\Users\gmathews\projects\winModule\windows\src\ComAppcModuleTest3.cpp(98): error C2789: 'usage': an object of const-qualified type must be initialized [C:\Users\gmathews\projects\winModule\windows\Windows10.ARM\ComAppcModuleTest3.vcxproj]
  C:\Users\gmathews\projects\winModule\windows\src\ComAppcModuleTest3.cpp(98): note: see declaration of 'usage'
C:\Users\gmathews\projects\winModule\windows\src\ComAppcModuleTest3.cpp(99): error C3536: 'usage': cannot be used before it is initialized [C:\Users\gmathews\projects\winModule\windows\Windows10.ARM\ComAppcModuleTest3.vcxproj]
C:\Users\gmathews\projects\winModule\windows\src\ComAppcModuleTest3.cpp(99): error C2227: left of '->ToString' must point to class/struct/union/generic type [C:\Users\gmathews\projects\winModule\windows\Windows10.ARM\ComAppcModuleTest3.vcxproj]
  C:\Users\gmathews\projects\winModule\windows\src\ComAppcModuleTest3.cpp(99): note: type is 'int'
C:\Users\gmathews\projects\winModule\windows\src\ComAppcModuleTest3.cpp(108): error C2653: 'SAP': is not a class or namespace name [C:\Users\gmathews\projects\winModule\windows\Windows10.ARM\ComAppcModuleTest3.vcxproj]
C:\Users\gmathews\projects\winModule\windows\src\ComAppcModuleTest3.cpp(108): error C2065: 'V4': undeclared identifier [C:\Users\gmathews\projects\winModule\windows\Windows10.ARM\ComAppcModuleTest3.vcxproj]
C:\Users\gmathews\projects\winModule\windows\src\ComAppcModuleTest3.cpp(108): error C2228: left of '.ToString' must have class/struct/union [C:\Users\gmathews\projects\winModule\windows\Windows10.ARM\ComAppcModuleTest3.vcxproj]
  C:\Users\gmathews\projects\winModule\windows\src\ComAppcModuleTest3.cpp(108): note: type is 'unknown-type'
```

If I open the project in Visual Studio and add the references manually, everything works great!

**Comment by infosia** [comment]
@garymathews Updated 👍

**Comment by infosia** [comment]
Note: Do not merge this, because this PR changes are already merged along with #967

**Comment by infosia** [comment]
Verified. Closing.

**Pull request closed without merging**
