### PR TITLE
[TIMOB-23439] Improve exception handling in async function

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-23439](https://jira.appcelerator.org/browse/TIMOB-23439)

Improve exception handling in async function

* Use `concurrency::task::get()` whenever possible so we can catch the exception
* Make sure we prefer to catch `Platform::Exception^` over `Platform::COMException^`

### CODE REVIEW

**Comment by infosia** [comment]
build win 10

**Comment by infosia** [comment]
build win 10

**Comment by garymathews** [comment]
test this please

**Comment by garymathews** [comment]
Looks good! :+1:

**Pull request merged**
