### PR TITLE
TitaniumKit performance optimization

### PR DESCRIPTION
**Pull request by infosia**
The [single context mode](https://github.com/appcelerator/HAL/pull/63) and [retain count management](https://github.com/appcelerator/HAL/pull/64) I introduced in the latest HAL provides huge performance improvement in TitaniumKit. I  have observed it cuts down over ~~50%~~ 70% of time.

On Lumia 630 (Windows Phone 8.1) using Ti SDK 6.0.0.v20160714010528

- Ti SDK 6.0.0.v20160714010528 ... 5.5 sec
- Ti SDK 6.0.0.v20160714010528 with this update ... ~~2.7 sec~~ -> 1.7 sec

```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green' });
var data = [];

var start = +new Date();
for (var i = 0; i < 100; i++) {
    var task = {
        Id: i,
        Title: 'Row ' + i,
        Data: 'Data ' + i
    };
    var tvr = Ti.UI.createTableViewRow({
        height: 70,
        taskId: task.Id
    });
    tvr.add(Ti.UI.createLabel({
        text: task.Title,
        color: "#000",
        top: 5,
        left: 20
    }));
    tvr.add(Ti.UI.createLabel({
        text: task.Data,
        color: "#000",
        top: 30,
        left: 20,
        font: {
            fontSize: 12
        }
    }));
    data.push(tvr);
}

var table = Ti.UI.createTableView({data: data});

table.addEventListener('click', function (e) {
    alert(e.row.taskId)
});

alert('Total: ' + (+new Date() - start));

win.add(table);
win.open();
```

I have also added performance improvement for TableView.

### CODE REVIEW

**Comment by garymathews** [comment]
test this please

**Comment by garymathews** [comment]
Awesome! :+1: 

WITHOUT: 5.532s
WITH: 2.750s (~50%)

CR: **PASS**
FR: **PASS**

**Comment by infosia** [comment]
hmm build went unstable. Looking into it.

**Comment by infosia** [comment]
I recently found out that TitaniumKit starts actively collecting garbages in single context mode, which is good. 😄 But it also reveals some other mistakes...fixing it.

destructor

**Comment by infosia** [comment]
Pushed more performance improvement. This basically let HAL manage `JSValue`/`JSObject` retain count, and reduce issuing `JSValue(Un)Protect` as much as possible. I can see this gains 20~30% performance improvement.

So we can see 70% performance improvement in total❗ 

`5.5` sec -> `2.7` sec -> `1.7` sec

**Comment by infosia** [comment]
Hmm Jenkins still gives me a random crash. investigating...

**Comment by infosia** [comment]
I can see now some tests starts freezing on Windows 10 desktop for some reason. I'm not sure why but I would just skip it for now as we've been seeing similar cases already...

**Comment by sgtcoolguy** [comment]
@infosia Sometimes the Windows 10 machines get stuck in UI tests because something hijacks focus from the emulator (like Java update or Windows update). I can try and RDP in and see..

**Comment by sgtcoolguy** [comment]
Windows update was hijacking the UI just now because it wants to restart. I scheduled it to restart in like 5 hours. (9:30pm PDT)

**Comment by infosia** [comment]
build win 10

**Pull request merged**
