### PR TITLE
[TIMOB-19186] Optimize getAppInfo()

### PR DESCRIPTION
**Pull request by garymathews**
- If ```_app_info_.json``` does not exist, don't keep attempting to load it

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19186)

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
@garymathews I could be wrong, but this doesn't seem to address the issue where we load the file multiple times, once per property instead of just loading the file once and grabbing the underlying values from the json. I could swear that has always been the case, regardless of the use of static keyword on the json var.

**Comment by garymathews** [comment]
I will look into this to see if that's happening.

**Comment by garymathews** [comment]
Ok, I've addressed the issue. Very strange issue with ```static``` variables inside the function. It was only the _second_ call that changed the variables value.

**Comment by sgtcoolguy** [comment]
@garymathews OK to merge once build passes

**Comment by infosia** [comment]
Looks good, merging.

**Pull request merged**
