### PR TITLE
Ti.Platform tweaks

### PR DESCRIPTION
**Pull request by sgtcoolguy**
Get processor count, add FIXME about architecture, report availableMemory on Phone

I was playing around seeing if it's feasible to implement a node-compatible native "os" module and needed some values we report from Ti.Platform. We seem to be lacking some of them, so I tried to fix a couple.

### CODE REVIEW

**Comment by dawsontoth** [comment]
Is this a WIP, or ready to be merged?

**Comment by sgtcoolguy** [comment]
@dawsontoth ready to be merged now, assuming the build passes

**Comment by dawsontoth** [comment]
Looks good; cr and fr passed.

**Comment by dawsontoth** [comment]
```javascript
var win = Ti.UI.createWindow();
win.add(Ti.UI.createLabel({
	text: 'Information:\n'
	+ 'processorCount: ' + Ti.Platform.processorCount + '\n'
	+ 'netmask: ' + Ti.Platform.netmask + '\n'
	+ 'availableMemory: ' + Ti.Platform.availableMemory + '\n'
	+ 'architecture: ' + Ti.Platform.architecture + '\n'
	+ 'address: ' + Ti.Platform.address + '\n'

}));
win.open();
```

**Pull request merged**
