### PR TITLE
[TIMOB-26464] Add Ti.UI.Window.safeAreaPadding and extendSafeArea

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-26464](https://jira.appcelerator.org/browse/TIMOB-26464)

Add `safeAreaPadding` and `extendSafeArea` property for `Ti.UI.Window`.

On Windows, we just hard-code the padding to all zeros because safe are is just not supported on Windows. I wouldn't update the API doc to state these properties are "supported" because these properties only intend to be a placeholder on Windows just to make sure use of these properties doesn't cause runtime errors.

```js
Ti.API.info(JSON.stringify(win.safeAreaPadding));
Ti.API.info(win.extendSafeArea);
```

Expected: `safeAreaPadding` returns empty padding. `extendSafeArea` defaults to `false`.

```
[INFO] {"bottom":0,"left":0,"right":0,"top":0}
[INFO] false
```

### CODE REVIEW

**Comment by jquick-axway** [comment]
Returning an empty padding is perfect.
Also, the "extendSafeArea" property is a creation-only property.

**Comment by infosia** [comment]
Unfortunately on Windows TitaniumKit framwork, creation-only property never work actually. It is forced to be normal read-write property.

**Comment by jquick-axway** [comment]
@infosia, how are we supposed to update the API docs to indicate Windows supports this in 8.0.0? Do we update the yml file in this repo?

**Comment by infosia** [comment]
@jquick-axway Yes, we need to update [Titanium/UI/Window.yml](https://github.com/appcelerator/titanium_mobile_windows/blob/master/apidoc/Titanium/UI/Window.yml) in that case.

**Comment by ssjsamir** [comment]
@infosia Cam be merged once Jenkins is ready.

**Pull request merged**
