### PR TITLE
[TIMOB-19961] [TIMOB-19956] ListView/TableView missing functions/properties

### PR DESCRIPTION
**Pull request by infosia**
[[TIMOB-19961](https://jira.appcelerator.org/browse/TIMOB-19961)] Implement TableView functions
[[TIMOB-19956](https://jira.appcelerator.org/browse/TIMOB-19956)] header/footer View for ListView

- Adds unit tests for ListView/TableView
- Introduces common data model ([ListModel](https://github.com/infosia/titanium_mobile_windows/blob/5cdeb088dcd6b7c3ca8e75925da7025228d42cc1/Source/TitaniumKit/include/Titanium/UI/ListModel.hpp)) for ListView and TableView

### CODE REVIEW

**Comment by infosia** [comment]
## Test Code

### ListView with header, footer and SearchBar

```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green', layout: 'vertical' }),
    listView = Ti.UI.createListView({
        width: Ti.UI.FILL, height: '80%'
    }),
    ukHeaderView = Ti.UI.createView({ backgroundColor: 'black', height: 42 }),
    ukFooterView = Ti.UI.createView({ backgroundColor: 'black', height: 42 }),
    ukSection = Ti.UI.createListSection({ headerView: ukHeaderView, footerView: ukFooterView }),
    usSection = Ti.UI.createListSection({ headerTitle: 'English US Header', footerTitle: 'English US Footer' });

var searchBar = Ti.UI.createSearchBar({
    width: Ti.UI.FILL,
    height: '10%'
});

listView.searchView = searchBar;

ukHeaderView.add(Ti.UI.createLabel({ text: 'English UK Header', color: 'white' }));
ukFooterView.add(Ti.UI.createLabel({ text: 'English UK Footer', color: 'white' }));
ukSection.setItems([
    { properties: { title: 'Lift', color: 'black' } },
    { properties: { title: 'Lorry', color: 'black' } },
    { properties: { title: 'Motorway', color: 'black' } }
]);
listView.appendSection(ukSection);

usSection.setItems([
    { properties: { title: 'Elevator', color: 'black' } },
    { properties: { title: 'Truck', color: 'black' } },
    { properties: { title: 'Freeway', color: 'black' } }
]);
listView.appendSection(usSection);

listView.addEventListener('itemclick', function (e) {
    alert(JSON.stringify(listView.sections[e.sectionIndex].items[e.itemIndex].properties));
});

win.add(searchBar);
win.add(listView);
win.open();
```

### ListView Sections

```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green' });
var listView = Ti.UI.createListView();
var sections = [];

var fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits' });
var fruitDataSet = [
    { properties: { title: 'Apple' } },
    { properties: { title: 'Banana' } },
];
fruitSection.setItems(fruitDataSet);
sections.push(fruitSection);

var vegSection = Ti.UI.createListSection({ headerTitle: 'Vegetables' });
var vegDataSet = [
    { properties: { title: 'Carrots' } },
    { properties: { title: 'Potatoes' } },
];
vegSection.setItems(vegDataSet);
sections.push(vegSection);

listView.sections = sections;
win.add(listView);
win.open();

var fishSection = Ti.UI.createListSection({ headerTitle: 'Fish' });
var fishDataSet = [
    { properties: { title: 'Cod' } },
    { properties: { title: 'Haddock' } },
];
fishSection.setItems(fishDataSet);
listView.appendSection(fishSection);
```

### TableView Sections

```javascript
Ti.UI.backgroundColor = 'green';
var win = Ti.UI.createWindow();

var sectionFruit = Ti.UI.createTableViewSection({ headerTitle: 'Fruit' });
sectionFruit.add(Ti.UI.createTableViewRow({ title: 'Apples' }));
sectionFruit.add(Ti.UI.createTableViewRow({ title: 'Bananas' }));

var sectionVeg = Ti.UI.createTableViewSection({ headerTitle: 'Vegetables' });
sectionVeg.add(Ti.UI.createTableViewRow({ title: 'Carrots' }));
sectionVeg.add(Ti.UI.createTableViewRow({ title: 'Potatoes' }));

var table = Ti.UI.createTableView({
    data: [sectionFruit, sectionVeg]
});

table.addEventListener('click', function (e) {
    alert(JSON.stringify(e.rowData.title));
});

win.add(table);
win.open();

var sectionFish = Ti.UI.createTableViewSection({ headerTitle: 'Fish' });
sectionFish.add(Ti.UI.createTableViewRow({ title: 'Cod' }));
sectionFish.add(Ti.UI.createTableViewRow({ title: 'Haddock' }));

table.insertSectionBefore(0, sectionFish);
```

**Comment by sgtcoolguy** [comment]
test this please

**Comment by garymathews** [comment]
Missing ```Titanium.UI.TableView.footerTitle``` and ```Titanium.UI.TableView.footerView```

```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'white' })
    primeSection = Ti.UI.createTableViewSection({ headerTitle: 'Prime Numbers Header', footerTitle: 'Prime Numbers Footer' }),
    fibSection = Ti.UI.createTableViewSection({ headerView: Ti.UI.createLabel({ text: 'Fibonacci Numbers Header' }), footerView: Ti.UI.createLabel({text: 'Fibonacci Numbers Footer'}) }),
    table = Ti.UI.createTableView({ data: [primeSection, fibSection] });

primeSection.add(Ti.UI.createTableViewRow({ title: '2' }));
primeSection.add(Ti.UI.createTableViewRow({ title: '3' }));
primeSection.add(Ti.UI.createTableViewRow({ title: '5' }));
primeSection.add(Ti.UI.createTableViewRow({ title: '7' }));

fibSection.add(Ti.UI.createTableViewRow({ title: '1' }));
fibSection.add(Ti.UI.createTableViewRow({ title: '1' }));
fibSection.add(Ti.UI.createTableViewRow({ title: '2' }));
fibSection.add(Ti.UI.createTableViewRow({ title: '3' }));

win.add(table);
win.open();
```

**Comment by infosia** [comment]
Cool, I'll be working on those missing properties in subsequent PR. ([TIMOB-19962](https://jira.appcelerator.org/browse/TIMOB-19962))

**Comment by garymathews** [comment]
##### Windows 8.1
- The first index of the list is automatically selected and cannot be unselected, should we default the selection mode to none? ```listview__->SelectionMode = Controls::ListViewSelectionMode::None;```

Windows Store 8.1

**Comment by infosia** [comment]
@garymathews nice catch. I'll be working on it.

**Comment by infosia** [comment]
Subsequent ticket for missing properties/functions: [TIMOB-19962](https://jira.appcelerator.org/browse/TIMOB-19962)

**Pull request merged**
