### PR TITLE
[TIMOB-19086] [TIMOB-19091] [TIMOB-19092] [TIMOB-19093] Various PFX Fixes

### PR DESCRIPTION
**Pull request by dawsontoth**
https://jira.appcelerator.org/browse/TIMOB-19086
https://jira.appcelerator.org/browse/TIMOB-19091
https://jira.appcelerator.org/browse/TIMOB-19092
https://jira.appcelerator.org/browse/TIMOB-19093

### CODE REVIEW

**Comment by ingo** [comment]
FYI. If you can tag the PR, it links to the tickets.

**Comment by dawsontoth** [comment]
But that title is so ugly...

**Comment by ingo** [comment]
Well, you could fix one ticket per PR :)

**Comment by dawsontoth** [comment]
:P

**Pull request merged**
