### PR TITLE
[TIMOB-25561] Error if apiversion is incorrect

### PR DESCRIPTION
**Pull request by ewanharris**
https://jira.appcelerator.org/browse/TIMOB-25561

### CODE REVIEW

**Comment by mukherjee2** [comment]
@garymathews would you be able to CR this one?

**Comment by mukherjee2** [comment]
@ewanharris After it passes review, I'll merge it, but the merge button is grayed out. Can you look into it?

**Comment by ewanharris** [comment]
@mukherjee2  There was an error removing the dist folder during building the SDK (not test related), I've just kicked Jenkins again hopefully it runs through fine

**Comment by sgtcoolguy** [comment]
LGTM 👍

**Pull request merged**
