### PR TITLE
Add unit test case for TIMOB-18684 - NOT READY FOR MERGE

### PR DESCRIPTION
**Pull request by infosia**
Unit test for [TIMOB-18684](https://jira.appcelerator.org/browse/TIMOB-18684). Related to #204.
Also added `load` event for `Ti.UI.ImageView` which is fired when image is loaded.

### CODE REVIEW

**Comment by infosia** [comment]
mocha test is failing but I can not reproduce this...looks like unit test timeouts before `postlayout`?

**Comment by ingo** [comment]
@muhammaddadu how do I add Kota as an employee again?

**Comment by sgtcoolguy** [comment]
@infosia Not sure why the test results don't show the error, but looking at the build logs when that test runs, I see:
```
Started: layoutWithSIZE_and_fixed
[INFO] :   Got focus event
[ERROR] :  Application Error: {
[ERROR] :    "message": "Runtime Error during postlayout event: expected 2896490496 to equal 50"
[ERROR] :  }
```

**Comment by infosia** [comment]
I think it's good to go, please review. This also fixes crash issue on Release build [TIMOB-18790](https://jira.appcelerator.org/browse/TIMOB-18790).

**Comment by infosia** [comment]
Oops I broke something again...debugging.

**Comment by infosia** [comment]
Ready now.

**Comment by infosia** [comment]
Close this, revised by #212

**Pull request closed without merging**
