### PR TITLE
Fix TIMOB-19177 Windows: Properties set in tiapp.xml not available via Ti.App.Properties API

### PR DESCRIPTION
**Pull request by sgtcoolguy**
https://jira.appcelerator.org/browse/TIMOB-19177

### CODE REVIEW

**Comment by infosia** [comment]
Jenkins reported failure, looks like `test.js` failed to create new project. @sgtcoolguy Any ideas why this happens?

```
08:50:56 C:\Jenkins\workspace\titanium_mobile_windows_prs\Tools\Scripts\build>call node test.js 
08:50:56 Installing SDK from master branch
08:50:57 Titanium Command-Line Interface, CLI version 4.1.2, Titanium SDK version 4.2.0.v20150728015233
08:50:57 Copyright (c) 2012-2015, Appcelerator, Inc.  All Rights Reserved.
08:50:57 Please report bugs to http://jira.appcelerator.org/
08:51:00 You're up-to-date. Version 4.2.0.v20150728015233 is currently the newest version available.
08:51:00 Run 'titanium sdk install 4.2.0.v20150728015233 --force --branch master' to re-install.
08:51:01 Copying built Windows SDK into master SDK
08:51:26 Generating Windows project
08:51:29 [31mFailed to create project[39m
```

**Comment by sgtcoolguy** [comment]
@infosia Yeah. I'm not sure why it's failing. I tried on my own Windows box using the exact same script and revision and it worked fine. Seems specific to the build agent. I'll have to take a deeper look tomorrow morning by VPNing to the build agent and trying to run the script manually and see if there's any more logs I can get out of it for the failure. I have a feeling it _may_ be something caused by Titanium Mobile changes.

**Comment by sgtcoolguy** [comment]
test this please.

**Comment by sgtcoolguy** [comment]
@infosia fixed up the build machine, this should be ready to review.

**Pull request merged**
