### PR TITLE
[TIMOB-20035] Implement Ti.Media.AudioPlayer.allowBackground

### PR DESCRIPTION
**Pull request by garymathews**
- Implemented ```Titanium.Media.AudioPlayer.allowBackground``` functionality
- Added ```AudioBackground``` background task to ```TitaniumWindows_Media```
- Fixed ```CurrentStateChanged``` switch statement
- Added ```Extentions``` support into ```tiapp.xml``` to enable the audio background task

##### IMPORTANT NOTE
- Both Windows Phone and Windows Store apps require an ```Audio``` _BackgroundTask_ extension in the ```Package.appxmanifest```
- Background audio plays from a separate media player [BackgroundMediaPlayer](https://msdn.microsoft.com/en-us/library/windows/apps/windows.media.playback.backgroundmediaplayer.current.aspx) which means we need to switch between media players when setting the ```allowBackground``` property

###### tiapp.xml Background Audio Extention
```XML
<windows>
  <manifest>
    <Extentions>
      <Extension Category="windows.backgroundTasks" EntryPoint="TitaniumWindows_Media.AudioBackground">
        <BackgroundTasks>
          <Task Type="audio" />
        </BackgroundTasks>
      </Extension>
    </Extentions>
  </manifest>
</windows>
```

###### TEST CASE
```Javascript
var audioPlayer = Ti.Media.createAudioPlayer({url: 'http://media-the.musicradio.com:80/SmoothExtraMP3'}),
    win = Titanium.UI.createWindow({backgroundColor: 'red'}),
    play_btn = Titanium.UI.createButton({title: 'play/pause', top: '33%'}),
    background_btn = Titanium.UI.createButton({title: 'allowBackground: false', top: '66%'});

play_btn.addEventListener('click', function() {
    audioPlayer.isPlaying() ? audioPlayer.stop() : audioPlayer.start();
});
background_btn.addEventListener('click', function() {
    audioPlayer.setAllowBackground(!audioPlayer.allowBackground);
    background_btn.setTitle('allowBackground: ' + audioPlayer.allowBackground);
});

win.add(play_btn);
win.add(background_btn);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20035)

### CODE REVIEW

**Comment by garymathews** [comment]
test this please

**Comment by infosia** [comment]
@garymathews I'm afraid it's not documented well, but basic support for platform-specific properties are implemented in [generate.js](https://github.com/appcelerator/titanium_mobile_windows/blob/master/cli/commands/_build/generate.js#L263) and [manifest templates](https://github.com/appcelerator/titanium_mobile_windows/blob/master/templates/build/Package.phone.appxmanifest.in.ejs) like this: https://github.com/appcelerator/titanium_mobile_windows/pull/278#issuecomment-112233996

```xml
<windows>
    <manifest target="phone">
        <Capabilities>
            <Capability Name="location" />
        </Capabilities>
    </manifest>
    <manifest target="store">
        <Capabilities>
            <Capability Name="optical" />
        </Capabilities>
    </manifest>
    <manifest>
        <Capabilities>
            <Capability Name="internetClient" />
        </Capabilities>
    </manifest>
</windows>
```

For now only `Properties`, `Capabilities`, `Prerequisites` and `Resources` are supported, so you need to add `Extension` support in `generate.js`.

**Comment by infosia** [comment]
CR: pass, FT: pass
awesome!

**Comment by infosia** [comment]
Just noticed a typo in the Gary's note, use *Extensions* instead of *Extentions*.

##### IMPORTANT NOTE

To enable background audio, both Windows Phone and Windows Store apps require an `Audio` BackgroundTask extension in the `tiapp.xml`

###### tiapp.xml Background Audio Extention

```xml
<windows>
  <manifest>
    <Extensions>
      <Extension Category="windows.backgroundTasks" EntryPoint="TitaniumWindows_Media.AudioBackground">
        <BackgroundTasks>
          <Task Type="audio" />
        </BackgroundTasks>
      </Extension>
    </Extensions>
  </manifest>
</windows>
```

**Pull request merged**
