### PR TITLE
[TIMOB-25281] Allow Ti.Media.saveToPhotoGallery to accept Ti.Blob

### PR DESCRIPTION
**Pull request by garymathews**
- Allow `Titanium.Media.saveToPhotoGallery` to accept `Titanium.Blob` objects
- Fix `Titanium.Filesystem.File.name` to return filename instead of full path

###### TEST CASE
```JS
var win = Ti.UI.createWindow(),
    view = Ti.UI.createView({
        backgroundColor: 'red',
        width: 400,
        height: 400,
        borderRadius: 200
    });

view.toImage(function(image) {
    Ti.Media.saveToPhotoGallery(image, {
        success: function (e) {
            console.log('success');
        },
        error: function (e) {
            console.error(JSON.stringify(e, null, 2));
        }
    });
});

win.add(view);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25281)

### CODE REVIEW

**Comment by longton95** [comment]
@garymathews I am still seeing a crash with the sample code above.

**Comment by infosia** [comment]
I tried this with latest build today and it went well on ws-local for me. @longton95 Would you try latest build [PR-1133/12/artifacts](https://jenkins.appcelerator.org/blue/organizations/jenkins/titanium-sdk%2Ftitanium_mobile_windows/detail/PR-1133/12/artifacts)?

**Comment by longton95** [comment]
@infosia the application still crashes for me, this is my environment

```
SDK Version : Local 7.0.0
Visual Studio 2017 (15.4.4)
Windows 10 Pro (1703)
Lumia 550 (10.0.15254.1)
Emulator (10.0.14393.0, 10.0.15063.0)
ws-local
Appc CLI : 7.0.0-master.8
Appc NPM : 4.2.11-2
Node : v8.9.1
```

**Comment by ssjsamir** [comment]
@infosia on my windows 10 device (lumia 50 - 10.0.15063.0) The application launches and shows a red circle but then the application closes. Do permissions need to be set to access the gallery?

**Comment by ewanharris** [comment]
@ssjsamir I think you're on the money, my bad on the ticket there sorry, try adding this to tiapp 

```xml
<windows>
    <manifest>
        <Capabilities>
            <Capability Name="internetClient" />    
             <Capability Name="picturesLibrary" />
        </Capabilities>
    </manifest>
</windows>
```

**Pull request merged**
