### PR TITLE
[TIMOB-23512] [TIMOB-23543] Relative require() from sub-directory fails

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-23512](https://jira.appcelerator.org/browse/TIMOB-23512) and [TIMOB-23543](https://jira.appcelerator.org/browse/TIMOB-23543)

### app.js
```javascript
var test = require('subdir/index');
should(test.filename).eql('/subdir/index.js');
should(test.name).eql('index.js');
should(test.sub).eql('sub.js');
```

### subdir/index.js

```javascript
var sub = require('./sub')
module.exports = {
    filename: __filename,
    name: 'index.js',
    sub: sub.name
};
```

### subdir/sub.js

```javascript
module.exports = {
    name: 'sub.js',
};
```

Note: In  order to retrieve current file name from requiring object, I ended up adding new hidden variable `__TI_REQUIRED__` in global object, which is only available while evaluating required module. This is tricky but needed because `JSObject parent` in `GlobalObject::requestResolveModule(parent, moduleId)` is always global object. (See also [Source/TitaniumKit/src/GlobalObject.cpp ](https://github.com/appcelerator/titanium_mobile_windows/pull/750/files#diff-3b6d0c60899ff30352e5cc386b90fa56R270))

### CODE REVIEW

**Comment by garymathews** [comment]
CR: **PASS**
FR: **PASS**

###### TEST CASE
```Javascript
var test = require('with_index_js');
Ti.API.info('with_index_js: ' + test.name);
```
```
[INFO] sub.name: sub.js
[INFO] with_index_js: index.js
```

**Comment by sgtcoolguy** [comment]
test this please

**Comment by sgtcoolguy** [comment]
@infosia Normal titanium builds look good. I think the native TitaniumKit tests need to be updated.

**Comment by infosia** [comment]
This PR includes `__filename` fix [TIMOB-23543](https://jira.appcelerator.org/browse/TIMOB-23543) but I'm not quite clear on the spec for Windows. See my comment in [TIMOB-23543](https://jira.appcelerator.org/browse/TIMOB-23543).

**Comment by sgtcoolguy** [comment]
@infosia Your implementation looks correct.

**Pull request merged**
