### PR TITLE
HTTPClient GET on an incorrect URL throws onload instead of onerror

### PR DESCRIPTION
**Pull request by sgtcoolguy**
https://jira.appcelerator.org/browse/TIMOB-19042

### CODE REVIEW

**Comment by infosia** [comment]
test this please

**Comment by yuchi** [comment]
A 404 is a perfectly good response, it must **not** fire `onerror`.

**Comment by sgtcoolguy** [comment]
As per our other platforms - we should fire onerror if the code is 400-599. The bug here is that we should do so only if an onerror handler is registered, otherwise we fire onload. I need to fix this PR to check that.

- Chris

On Jun 24, 2015, at 8:00 AM, Pier Paolo Ramon <notifications@github.com<mailto:notifications@github.com>> wrote:


A 404 is a perfectly good response, it must not fire onerror.

-

**Comment by infosia** [comment]
Looks good, once all tests passed. I believe build failure on Travis is already fixed by #320.

**Comment by sgtcoolguy** [comment]
Merged manually.

**Comment by yuchi** [comment]
I'm afraid the HTTPClient diverges too much from XmlHTTPRequests.

**Pull request closed without merging**
