### PR TITLE
[TIMOB-24869] ShowCamera should not write image to photoGallery by default

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-24869](https://jira.appcelerator.org/browse/TIMOB-24869)

`Ti.Media.showCamera` should respect `CameraOptionsType.saveToPhotoGallery` config, which is `false` by default.

```js
var win = Ti.UI.createWindow({ backgroundColor: 'green', layout: 'vertical' }),
    openButton = Ti.UI.createButton({ title: 'OPEN CAMERA', backgroundColor: 'blue' }),
    imageView = Ti.UI.createImageView({ width: Ti.UI.FILL, height: '80%' });

openButton.addEventListener('click', function () {
    Ti.Media.showCamera({
        // saveToPhotoGallery: true, // uncomment to this save to photo gallery
        mediaTypes: [Ti.Media.MEDIA_TYPE_PHOTO],
        success: function (e) {
            imageView.image = e.media;
        },
        error: function (e) {
            alert('showCamera() error: ' + JSON.stringify(e));
        }
    });
});

win.add(openButton);
win.add(imageView);
win.open();
```

Note: Additional `Capability` should be declared in `tiapp.xml`. 

```xml
<DeviceCapability Name="webcam" />
<Capability Name="picturesLibrary" />
```

Expected: Taken photo should be shown but should not be saved to photo gallery.

### CODE REVIEW

**Comment by ewanharris** [comment]
@infosia When using a custom overlay the image is still saved to the photo gallery by default, the overlay + Ti.Media.takePicture setup takes a different path to the default native camera https://github.com/infosia/titanium_mobile_windows/blob/e7d18127184fa693a94333ac5e28d45ed2630322/Source/Media/src/Media.cpp#L795-L866

````js
var win = Ti.UI.createWindow({ backgroundColor: 'green' }),
    openButton = Ti.UI.createButton({ title:'OPEN CAMERA', backgroundColor:'blue' }).
    overlay = Ti.UI.createView({ layout: 'vertical', height: '20%', width: Ti.UI.FILL, bottom: 0}),
	takeButton = Ti.UI.createButton({ title: 'TAKE A PHOTO', backgroundColor: 'red' }),
	hideButton = Ti.UI.createButton({ title: 'HIDE PREVIEW', backgroundColor: 'red' });
takeButton.addEventListener('click', function () {
    Ti.Media.takePicture();
});
hideButton.addEventListener('click', function () {
    Ti.Media.hideCamera();
});
overlay.add(takeButton);
overlay.add(hideButton);
openButton.addEventListener('click', function () {
    Ti.Media.showCamera({
        mediaTypes: [Ti.Media.MEDIA_TYPE_PHOTO],
        overlay: overlay,
        success: function (e) {
            Ti.API.info('showCamera() success');
        },
        error: function () {
            Ti.API.info('showCamera() error');
        }
    });
});
win.add(openButton);
win.open();
````

**Comment by infosia** [comment]
@ewanharris Nice! Updated.

**Comment by infosia** [comment]
This also resolves [TIMOB-24985](https://jira.appcelerator.org/browse/TIMOB-24985)

**Comment by ewanharris** [comment]
@garymathews  If you have time could you do a CR on a157546e9751f1b13688636eae1fc4698e74788b

**Comment by garymathews** [comment]
@infosia Backport to `6.2.0`

**Pull request merged**
