### PR TITLE
[TIMOB-23775] Impose restrictions on feature events

### PR DESCRIPTION
**Pull request by garymathews**
- Impose restrictions on feature event data object
  - Number of nested levels: `5`
  - Maximum object size: `1000`
  - Number of keys per level: `35`
  - Maximum key length: `50`
- Renamed `toAnalyticsDate()` into `toSimpleDateFormat()` and improved description
- `featureEvent` returns success result
- Add `ti.analytics.test.js` test case

###### TEST CASE
```Javascript
var win = Ti.UI.createWindow({backgroundColor: 'purple'}),
    btn_a = Ti.UI.createButton({title: 'Feature Event: exceed levels', top: 0}),
    btn_b = Ti.UI.createButton({title: 'Feature Event: invalid object', top: 50}),
    btn_c = Ti.UI.createButton({title: 'Feature Event: exceed size', top: 100}),
    btn_d = Ti.UI.createButton({title: 'Feature Event: exceed keys', top: 150}),
    btn_e = Ti.UI.createButton({title: 'Feature Event: exceed key length', top: 200});

btn_a.addEventListener('click', function () {
    var data = {};
    for (var l = 0; l < 6; l++) {
        data = {l: data};
    }
    Ti.Analytics.featureEvent('levels', data);
});
btn_b.addEventListener('click', function () {
    var data = undefined;
    Ti.Analytics.featureEvent('invalid', data);
});
btn_c.addEventListener('click', function () {
    var data = {big: Array(1002).join('c')};
    Ti.Analytics.featureEvent('size', data);
});
btn_d.addEventListener('click', function () {
    var data = {};
    for (var k = 0; k < 36; k++) {
        data[k] = 'd';
    }
    Ti.Analytics.featureEvent('keys', data);
});
btn_e.addEventListener('click', function () {
    var data = {};
    data[Array(52).join('e')] = 'e';
    Ti.Analytics.featureEvent('keyLength', data);
});

win.add(btn_a);
win.add(btn_b);
win.add(btn_c);
win.add(btn_d);
win.add(btn_e);

win.open();
```
```
[WARN] Feature event exceeds 5 level limit.
[WARN] Feature event data object is undefined.
[WARN] Feature event data object exceeds 1000 size limit.
[WARN] Feature event data object exceeds 35 key limit.
[WARN] Feature event data object key 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee' exceeds 50 key length limit.
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23775)

### CODE REVIEW

**Comment by infosia** [comment]
Can we add unit test for this? See attachment in [TIMOB-19826](https://jira.appcelerator.org/browse/TIMOB-19826) ([TIMOB-19826-test.zip](https://jira.appcelerator.org/secure/attachment/57932/TIMOB-19826-test.zip))

**Comment by infosia** [comment]
According to the doc ([api/Titanium.Analytics](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.Analytics)),  `featureEvent` should return number.

```
Returns
    Number
    It returns 0 if it is successful. Otherwise, it is an error.
```

**Comment by garymathews** [comment]
Nice catch! :+1:

Updated PR

**Comment by garymathews** [comment]
test this please

**Comment by infosia** [comment]
build win 8.1

**Pull request merged**
