### PR TITLE
[TIMOB-26019] Support x64 build target

### PR DESCRIPTION
**Pull request by infosia**
- [TIMOB-26019](https://jira.appcelerator.org/browse/TIMOB-26019)
- [TIMOB-25999](https://jira.appcelerator.org/browse/TIMOB-25999)

### Building x64 target using `--architecture x64` option.

```
appc run -p windows --target ws-local -l trace --architecture x64 --build-only
```

How to test:

1. Build app with `--architecture x64` option
2. Open `C:\Users\USERNAME\.titanium\vsbuild\PROJECT_NAME\win10.x64\PROJECT_NAME.sln`
3. Visual Studio should target `x64` platform (See screenshot below)

vs

### Building ARM target using `--architecture arm` option.

```
appc run -p windows --target ws-local -l trace --architecture arm --build-only
```

How to test:

1. Build app with `--architecture arm` option
2. Open `C:\Users\USERNAME\.titanium\vsbuild\PROJECT_NAME\win10.ARM\PROJECT_NAME.sln`
3. Visual Studio should target `ARM` platform

### x64 module support

How to test:

1. Create new module with `appc new`.
2. Build the module (`cd MODULE_PROJECT; cd windows;  appc ti build -p windows --build-only -l trace`
3. Use the module in `x64` project

### CODE REVIEW

**Comment by ewanharris** [comment]
@infosia Could the architecture switch maybe come from an option rather than a flag? Something like `-a/--architecture`, that way we can perform some validation, and only one architecture could be targeted per build for sure. We could also maybe do something similar to Android and [list the valid architectures](https://github.com/appcelerator/titanium_mobile/blob/master/android/package.json#L16), in the package.json which can be used in validation, when populating the modules manifest etc. to make maintenance a little easier?

**Comment by infosia** [comment]
@ewanharris Nice idea! Yes that sounds feasible, I'll be working on it 👍

**Comment by garymathews** [comment]
@infosia Could the conflicts be resolved?

**Comment by infosia** [comment]
@garymathews Thanks for the heads up. Fixed.

**Comment by infosia** [comment]
Closing this for now, it has been more than a year and the code is becoming obsolete.

**Pull request closed without merging**
