### PR TITLE
[TIMOB-20578] Add function to register push notification trigger

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-20578](https://jira.appcelerator.org/browse/TIMOB-20578)

Implement unified way to create/register [push notification trigger](https://msdn.microsoft.com/en-us/library/windows/apps/windows.applicationmodel.background.pushnotificationtrigger.aspx) for [Windows raw notification](https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-raw-notification-overview). API usage is very similar to what we did in [TimerTrigger](https://appcelerator.github.io/appc-docs/platform/latest/#!/guide/Windows_Background_Service_Quick_Start-section-46248264_WindowsBackgroundServiceQuickStart-ImplementBackgroundTask). For more information see [Windows Background Service Quick Start](https://appcelerator.github.io/appc-docs/platform/latest/#!/guide/Windows_Background_Service_Quick_Start).

Note that this only provides a basic way to register task. To make  [Windows raw notification](https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-raw-notification-overview) work, you'll need to do a lot of other tasks (i.e. setup [Windows Push Notification Services (WNS)](https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-raw-notification-overview) and request [notification channel](https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-windows-push-notification-services--wns--overview) etc. You might want to consider extending Titanium using native modules to implement client-side setup.

This PR also includes documentation for Windows background service API overall.

```javascript
  // Register new push notification task.
  var task = Ti.App.Windows.BackgroundService.registerPushNotificationTask('ComExampleTest.BackgroundServiceTask');
  if (task) {
    Ti.API.info('Background task is registered: task id=' + task.taskId);
  }
```

In order to enable push notification task, add `pushNotification` Task in `tiapp.xml`.

```xml
  <windows>
    <manifest>
      <Extensions>
        <Extension Category="windows.backgroundTasks" EntryPoint="ComExampleTest.BackgroundServiceTask">
          <BackgroundTasks>
            <Task Type="pushNotification" />
          </BackgroundTasks>
        </Extension>
      </Extensions>
    </manifest>
  </windows>
```

### CODE REVIEW

**Comment by Buder** [comment]
OK, got it (I think)

**Comment by garymathews** [comment]
FR: **PASS**

However, on Windows 8.1 ``Package.appxmanifest`` needs

``<m2:LockScreen Notification="badge" BadgeLogo="Logo.png" />``

in order to compile, where ``Logo.png`` is the icon used for notifications

**Comment by infosia** [comment]
That sounds familiar...looked back the commit log and found out it is [once added](573) but [removed recently](630). Sounds like CLI needs to be more wise to enable badge logo only when you enable background tasks.

**Comment by Buder** [comment]
Thanks Gary, so Kota is that all I have to do to enable it to build once we get it into nightly builds? 

I have changed the tiapp.xml with the extension, pointed it to a function in my current module:

<Extension Category="windows.backgroundTasks" EntryPoint="gws.extendwindows.getValues">
          <BackgroundTasks>
            <Task Type="pushNotification" />
          </BackgroundTasks>
        </Extension>

and have the code standby in my app, 

I will look how to set this up in backend at MS as well but additionally I need to add the logo in that file? Do I have to do that "every time" I build? Just thinking how that file is generated? Will it overwrite every time I push build in studio ? How do I override the file then? In /platform/ as usual ?

**Comment by Buder** [comment]
where do I find package.appxmanifest ?? :(

**Comment by infosia** [comment]
@Buder The badge logo will be generated based on `DefaultIcon.png` by Titanium CLI. So I think usually you don't have to be worried about it.

**Comment by Buder** [comment]
ok, thanks

Next problem, I do not have the class namespace in my current module and I remember I had trouble generating the module as I had to specify name id and some more data , the module create command you specify in the docs now generate an error on my side saying:

appc new -n test --id com.example.test

and then chose module
CMake error CMakeLists.txt:20 (project);

it says:

A Windows Phone component with CMake requires both the Windows Desktop SDK
as well as the Windows Phone '8.1' SDK.  Please make sure that you have
both installed

I have not had this problem before when I generated my module the "old" way... will try to find that, however is there other way I can get the class / namespace into my current module? Or does it have to be generated?

**Comment by Buder** [comment]
Oh, sorry that was probably more related ot the background task, but still I have that same problem generating the module at this stage, best thing for me right now would be to add the class into my current module and try using the callbacks from there..

**Comment by Buder** [comment]
I cannot find in your docs that I have to install a Windows Desktop SDK, and honestly I have never had that requirement before so far building phone 8.1 apps, and I can still do that , is this specifically for module generating or for module build as well?

I just tried to build my old module the standard way: ti build -p windows -T ws-local -l trace

and that works well

**Comment by Buder** [comment]
So I tried the "old" way to create the module but that gives me the same problem now:

ti create -p windows -t module -n test --id com.test.se

Is there something more I have to update ?

CLI appc / ti ?

should I do a appc setup?

:(

**Comment by Buder** [comment]
Ok, so I have the namespace class copied over to my module and everything configured, at one point I had my "old" module still running WITHOUT any background task extension, but I was indeed able to have the ref i extensions in manifest AND I had code registering the class, and it retuned task.id = 0 which should mean things worked, but the module was not build and updated, so there cannot have been anything working... in any case I found out that the module creation did not package my module, I had to go into the build directory and copy over the folder structure to my app instead of just copying the zip file (zip file = 0 bytes) skipping package ... since I was able to register a timed task before without class ref I also added your code with properties count, I will see if that one actually increases over time (may be a good thing to mention in the docs that a app that runs a background service HAS to have it pinned to the front desktop on the phone or it will not run).. I am testing now if indeed the class is registered..

**Comment by Buder** [comment]
Nope it is not building it correctly, even though I have no build errors... :(

**Comment by infosia** [comment]
@Buder That sounds like cmake failed to generate project files. Which version of Titanium SDK are you using?  `appc ti sdk select` will show it. Also, what does `node --version` show? I'm wondering if you are able to create new ticket in JIRA so you can add more info and track the issue. console output from ti create and `ti info -p windows` will always help diagnostic the issue.

**Comment by Buder** [comment]
So what you are saying is that i HAVE TO recreate my module, since you thing maybe the project files are not there? I mean the module has been built a 100 times before... let me try to revert and see what is the actual reason, I will create a new ticket as bug for this..

**Comment by sgtcoolguy** [comment]
The build containing Kota's changes didn't end up going out in any SDK release nightly yesterday. It should be available now. That's the likely reason.

**Comment by infosia** [comment]
build win 10

**Comment by Buder** [comment]
Hi, PLEASE see : https://jira.appcelerator.org/browse/TIMOB-23246

This is a critical problem for me I also posted all environment and trace when I try to create the modue but it does not help me too much.. :(

**Comment by infosia** [comment]
build win 10

**Comment by Buder** [comment]
Is this one now in the nightly builds so I can test it ?

Thanks

**Comment by Buder** [comment]
I am not sure I could see any module hook for it

**Pull request merged**
