### PR TITLE
[TIMOB-20236] Fix GetUriFromPath to handle local paths

### PR DESCRIPTION
**Pull request by garymathews**
- Fixed ```GetUriFromPath``` to handle local file paths

###### TEST CASE
```Javascript
var win = Ti.UI.createWindow({backgroundColor:'black'}),
    img = Ti.UI.createImageView({height:'50%'}),
    http = Titanium.Network.createHTTPClient({
        onload: function () {
            var f = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory, 'win.png');
            f.write(this.responseData);
            Ti.App.fireEvent('downloaded', { path: f.nativePath });
        },
        timeout: 3000
    });

http.open('GET', 'http://tinyurl.com/TIMOB-20236');
http.send();
Ti.App.addEventListener('downloaded', function (e) {
    img.image = e.path;
});
img.addEventListener('click', function () {
    img.image = 'Logo.png';
});
win.add(img);
win.open();
```

[TIMOB-20236](https://jira.appcelerator.org/browse/TIMOB-20236)

### CODE REVIEW

**Comment by infosia** [comment]
Works great for me when image is located under the application data directory. But it also should be able to accept application directory. I think it should accept following cases:

```javascript
// from application data directory (ms-appdata://)
img.image = Ti.Filesystem.applicationDataDirectory + Ti.Filesystem.separator + 'win.png';

// from application installed directory (ms-appx://)
img.image = Ti.Filesystem.applicationDirectory + Ti.Filesystem.separator + 'Logo.png';

// from relative path, load image directly under application directory (ms-appx://). 
img.image = 'Logo.png';

// how do we treat "absolute path"? I think we want to use ms-appx:// in this case.
img.image = '/Logo.png';

// I think we want to accept Windows-specific prefix too.
img.image = 'ms-appx://Logo.png';
img.image = 'ms-appdata://xxx/win.png';
```

Also, please make sure this does not cause regression on the other components which uses `GetUriFromPath`. (for instance `View.backgroundColor` uses it)

**Comment by garymathews** [comment]
@infosia Updated.

**Comment by garymathews** [comment]
test this please

**Comment by garymathews** [comment]
test this please

**Comment by infosia** [comment]
Looks good. ok to merge once Jenkins passes it.

**Comment by sgtcoolguy** [comment]
build win 10

**Comment by garymathews** [comment]
build win 10

**Comment by infosia** [comment]
I found that `img.image = Ti.Filesystem.applicationDirectory +'Logo.png'` does not work. I also found that default ImageView layouts set to `FILL` which needs to be `SIZE` actually. I will take over this and push new PR soon.

**Comment by infosia** [comment]
Closing, as taken over by #548

**Pull request closed without merging**
