### PR TITLE
Fix: Creating windows module errors out due to missing boost libraries

### PR DESCRIPTION
**Pull request by infosia**
Fix for [TIMOB-19108](https://jira.appcelerator.org/browse/TIMOB-19108).

### CODE REVIEW

**Comment by infosia** [comment]
Jenkins build failed, looks like it aborted around `windowslib`?

```
18:13:49 [INFO] :   Launching emulator: 8-1-1
18:13:49 
18:13:49 C:\Jenkins\workspace\titanium_mobile_windows_prs\Tools\Scripts\build\node_modules\titanium\node_modules\longjohn\dist\longjohn.js:195
18:13:49         throw e;
18:13:49               ^
18:13:49 RangeError: Invalid array length
18:13:49     at Readable.on (_stream_readable.js:671:33)
18:13:49     at once (events.js:204:8)
18:13:49     at Duplex (_stream_duplex.js:58:8)
18:13:49     at new Socket (net.js:150:17)
18:13:49     at createSocket (child_process.js:72:11)
18:13:49     at child_process.js:1171:22
18:13:49 ---------------------------------------------
18:13:49     at magik (C:\ProgramData\Titanium\mobilesdk\win32\4.2.0.v20150629140136\node_modules\windowslib\lib\utilities.js:33:10)
18:13:49     at Object.detect (C:\ProgramData\Titanium\mobilesdk\win32\4.2.0.v20150629140136\node_modules\windowslib\lib\windowsphone.js:42:9)
18:13:49     at EventEmitter.<anonymous> (C:\ProgramData\Titanium\mobilesdk\win32\4.2.0.v20150629140136\node_modules\windowslib\lib\wptool.js:219:18)
```

**Comment by dawsontoth** [comment]
Yeah, I've seen that on the other PRs as well. Not sure what it means.

**Comment by sgtcoolguy** [comment]
I _think_ it means we're running out of memory!

http://stackoverflow.com/questions/30520505/node-invalid-array-length

**Comment by sgtcoolguy** [comment]
The weird thing is that I can't reproduce it locally. You'd think it would always happen. 

Short of going through the code to see why we're running out of memory and where we might be able to refactor to release it as we go, I think a shorter term fix may be to make the async.each call in windowslib index.js use async.eachLimit and limit it to detect only like in parallel.

**Pull request merged**
