### PR TITLE
[TIMOB-23834] Optimize windowslib usage

### PR DESCRIPTION
**Pull request by garymathews**
- Only detect devices when targeting a windows device
  - Saves time when building for `ws-local` or `--build-only`
- Remove unnecessary `windowslib.detect()`

##### DEPENDS ON
- https://github.com/appcelerator/windowslib/pull/56

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23834)

### CODE REVIEW

**Comment by garymathews** [comment]
build win 10

**Comment by garymathews** [comment]
build win 10

**Comment by infosia** [comment]
Looks good 👍

**Comment by infosia** [comment]
I'll bump up `windowslib` version for `titanium_mobile` later.

**Pull request merged**
