### PR TITLE
[TIMOB-26791] Ti.UI.View top/left/bottom/right parity

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-26791](https://jira.appcelerator.org/browse/TIMOB-26791)

View layout properties such as `width` and `height` should return JS `Number` instead of `String` when it doesn't contain unit specifier like `px` and `%`. 

```js
var win = Ti.UI.createWindow({ backgroundColor: 'green' });

var label1 = Ti.UI.createLabel({
    width: 200, height: 50, left: 10, top: 10, text: 'Hello, World', font: { fontSize: 12 }
});

var label2 = Ti.UI.createLabel({
    width: '200px', height: '50px', left: '10px', top: '110px', text: 'Hello, World', font: { fontSize: '12px' }
});

var label3 = Ti.UI.createLabel({
    width: 200, height: 50, center: { x: '100px', y: '200px' }, text: 'Hello, World'
});

var label4 = Ti.UI.createLabel({
    width: 200, height: 50, left: 10, bottom: '50px', text: 'Hello, World'
});

win.add(label1);
win.add(label2);
win.add(label3);
win.add(label4);

win.addEventListener('open', function () {
    Ti.API.info('---------------------');
    Ti.API.info(typeof label1.width);
    Ti.API.info(typeof label1.height);
    Ti.API.info(typeof label1.left);
    Ti.API.info(typeof label1.top);
    Ti.API.info(typeof label1.bottom);
    Ti.API.info(typeof label1.center.x);
    Ti.API.info(typeof label1.center.y);
    Ti.API.info(typeof label1.font.fontSize);
    Ti.API.info('---------------------');
    Ti.API.info(typeof label2.width);
    Ti.API.info(typeof label2.height);
    Ti.API.info(typeof label2.left);
    Ti.API.info(typeof label2.top);
    Ti.API.info(typeof label2.font.fontSize);
    Ti.API.info('---------------------');
    Ti.API.info(typeof label3.center.x);
    Ti.API.info(typeof label3.center.y);
    Ti.API.info('---------------------');
    Ti.API.info(typeof label4.bottom);
    Ti.API.info('---------------------');

});

win.open();
```

Expected:

```
[INFO] ---------------------
[INFO] number
[INFO] number
[INFO] number
[INFO] number
[INFO] number
[INFO] number
[INFO] number
[INFO] number
[INFO] ---------------------
[INFO] string
[INFO] string
[INFO] string
[INFO] string
[INFO] string
[INFO] ---------------------
[INFO] string
[INFO] string
[INFO] ---------------------
[INFO] string
[INFO] ---------------------
```

### CODE REVIEW

**Comment by keerthi1032** [comment]
@infosia when doing FR found that  with master SDK or with sdk from this PR getting the following error and app is not launching.Can you please take a look . **"[DEBUG] :  Copying C:\Users\Test\Documents\Appcelerator_Studio_Workspace\testh\Resources\app.js => C:\Users\Test\.titanium\vsbuild\testh\Assets\app.js
2019-04-03T19:14:43.966Z | ERROR  | An uncaught exception was thrown!
ENOENT: no such file or directory, open 'C:\Users\Test\.titanium\vsbuild\testh\Assets\ti.internal\bootstrap.json'
2019-04-03T19:14:43.975Z | ERROR  | ENOENT: no such file or directory, open 'C:\Users\Test\.titanium\vsbuild\testh\Assets\ti.internal\bootstrap.json' "**

**Comment by infosia** [comment]
@keerthi1032 It seems Jenkins has been failing to package built artifacts correctly. Let me check.

**Comment by infosia** [comment]
@keerthi1032 The build should be fixed now. Please check the latest one.

**Comment by infosia** [comment]
Still failing for `master` :(

**Comment by infosia** [comment]
@keerthi1032 The PR build artifacts should be fixed now. Jenkins `master` is still failing but please use `8.0.0.GA` for now in case you want to reproduce the TIMOB-26791 issue.

**Comment by infosia** [comment]
`master` is fixed now.

**Comment by ssjsamir** [comment]
@infosia Can be merged once Jenkins is ready

**Pull request merged**
