### PR TITLE
[TIMOB-25178] [TIMOB-25174] ScrollView and Picker layout issues

### PR DESCRIPTION
**Pull request by infosia**
* [[TIMOB-25178](https://jira.appcelerator.org/browse/TIMOB-25178)] ScrollView.removeAllChildren does not work 

```js
var win = Ti.UI.createWindow({
    backgroundColor: 'white'
});

var scrollView = Ti.UI.createScrollView({
    height: '80%',
    width: '80%'
});
var view = Ti.UI.createView({
    backgroundColor: '#336699',
    top: 10,
    height: 2000,
    width: 1000
});
scrollView.add(view);

win.addEventListener('click', function () {
    scrollView.removeAllChildren();
});

win.add(scrollView);
win.open();
```

Expected: view should be removed from ScrollView when you click root Window

* [[TIMOB-25174](https://jira.appcelerator.org/browse/TIMOB-25174)] applyProperties throws exception on Picker 

```js
var win = Ti.UI.createWindow({
    backgroundColor: 'white'
});

var picker = Ti.UI.createPicker({
    top: 50,
    width:  '80%',
    height: '80%',
    backgroundColor: 'green'
});

var data = [];
data[0] = Ti.UI.createPickerRow({ title: 'Bananas' });
data[1] = Ti.UI.createPickerRow({ title: 'Strawberries' });
data[2] = Ti.UI.createPickerRow({ title: 'Mangos' });
data[3] = Ti.UI.createPickerRow({ title: 'Grapes' });

picker.add(data);

picker.applyProperties({ backgroundColor: 'red' })

win.add(picker);
win.open();
```

Expected: applyProperties should not throw exception

### CODE REVIEW

**Comment by ewanharris** [comment]
@infosia As this change wont be going into 6.2.0, just wanted to make sure you're good with this being merged into master meaning we'll need to do proper backports for any other possible tickets from now on

**Comment by infosia** [comment]
@ewanharris I'm good with this merged into master. 

> we'll need to do proper backports for any other possible tickets from now on

I'm not quite get it yet, which tickets in particular, which branch to backport?

**Comment by ewanharris** [comment]
@infosia There's nothing at the moment that requires a backport, it was just in case any tickets are filed after 6.2.0.RC is pushed, we'd have to properly cherry-pick the commits across rather than merging the branches. As you're good with that I'm gonna hit that merge button!

**Comment by infosia** [comment]
@ewanharris ok I see 👍

**Pull request merged**
