### PR TITLE
TIMOB-18855 Windows: Time between creating Date() objects runs a factor 1000 slower then reality

### PR DESCRIPTION
**Pull request by sgtcoolguy**
Update HAL to HEAD

### CODE REVIEW

**Comment by infosia** [comment]
Jenkins reported mocha test looks ok but marked "unstable"?

**Comment by sgtcoolguy** [comment]
@infosia Looks like due to new MSBuild warnings from JSC? http://studio-jenkins.appcelerator.org/job/titanium_mobile_windows_prs/963/warnings34Result/new/

**Comment by infosia** [comment]
It was because of `warning C4714` which only happens when you build against `Release|ARM`. Investigating...

**Comment by infosia** [comment]
@sgtcoolguy I've updated [JavaScriptCore-Windows-1430359270.zip](http://timobile.appcelerator.com.s3.amazonaws.com/jscore/JavaScriptCore-Windows-1430359270.zip) which should suppress these warnings. Could you try this one? It's safe to overwrite existing libraries.

**Comment by sgtcoolguy** [comment]
test this please

**Comment by sgtcoolguy** [comment]
test this please

**Comment by sgtcoolguy** [comment]
test this please

**Pull request merged**
