### PR TITLE
Implement missing functions/properties/events

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-19399](https://jira.appcelerator.org/browse/TIMOB-19399), [TIMOB-19401](https://jira.appcelerator.org/browse/TIMOB-19401) and [TIMOB-19404](https://jira.appcelerator.org/browse/TIMOB-19404). 

- Implement ScrollView TitaniumKit function/properties
- Implement View events (`click`, `doubleclick`, `touchstart`, `touchend`, `singletap`, `doubletap` and `longpress`)
- Fix ImageView layout parity

```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'blue' });
var view = Ti.UI.createView({
    backgroundColor: 'red',
    width: '50%', height:'50%'
});
var imageview = Ti.UI.createImageView({
    image: "http://image.tmdb.org/t/p/w780//3FweBee0xZoY77uO1bhUOlQorNH.jpg",
    width: Ti.UI.FILL, height: Ti.UI.FILL
});
view.add(imageview);
win.add(view);
win.open()
```

imageview

### CODE REVIEW

**Comment by infosia** [comment]
Added fix for [TIMOB-19409](https://jira.appcelerator.org/browse/TIMOB-19409).

```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'blue' });

var view = Ti.UI.createView({
    backgroundColor: 'red',
    width: 185, height: 185
});

var image = Ti.UI.createView({
    backgroundColor: 'yellow',
    top: -20, left: -185,
    width: 555, height: 312
});

var imageview = Ti.UI.createImageView({
    image: 'http://image.tmdb.org/t/p/w780//3FweBee0xZoY77uO1bhUOlQorNH.jpg',
    top: -20, left: -185,
    width: 555, height: 312
});
image.add(imageview);

view.add(image);
win.add(view);
win.open()
```

windows

**Comment by infosia** [comment]
Known issue on clipping: When target view is outside of the screen, it is not rendered correctly because Xaml `UIElement.Clip` can't capture view outside of the screen. Which means typically it usually doesn't work well with `ScrollView`. For instance following example shows bottom half of the image is "cut" because it was outside of the screen before scrolling.

```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'blue' });

var scrollView = Ti.UI.createScrollView({
    showVerticalScrollIndicator: true,
    showHorizontalScrollIndicator: true,
    height: '100%',
    width: '100%',
    contentHeight: 1000
});

var view1 = Ti.UI.createView({
    backgroundColor: 'red',
    width: 185, height: 185,
    top: 100
});
var imageview1 = Ti.UI.createImageView({
    image: 'http://image.tmdb.org/t/p/w780//3FweBee0xZoY77uO1bhUOlQorNH.jpg',
    top: -20, left: -185,
    width: 555, height: 312
});
view1.add(imageview1);

var view2 = Ti.UI.createView({
    backgroundColor: 'red',
    width: 185, height: 185,
    top: 550
});
var imageview2 = Ti.UI.createImageView({
    image: 'http://image.tmdb.org/t/p/w780//3FweBee0xZoY77uO1bhUOlQorNH.jpg',
    top: -20, left: -185,
    width: 555, height: 312
});
view2.add(imageview2);

scrollView.add(view1);
scrollView.add(view2);

win.add(scrollView);
win.open()
```

clip

**Comment by infosia** [comment]
@sgtcoolguy Do you have any good idea on how to do view clipping ([TIMOB-19409](https://jira.appcelerator.org/browse/TIMOB-19409))? I've tried to use [UIElement::Clip](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.uielement.clip), it worked in a certain case but I almost give up using it because

- `Clip` doesn't work when view is placed outside of the screen
- `Clip` can't be reverted, which causes issue when resizing view

**Comment by sgtcoolguy** [comment]
@infosia UIElement.Clip seems like the right API to me. What are the issues it has when the view is outside the screen (I assume this means that at least one edge is "beyond" the screen limit)? Why can't the Clip be reverted? We can't just set the Clip to a new Geometry with the same bounds as the object it was clipping before?

**Comment by infosia** [comment]
@sgtcoolguy So what I've seen is that when use with Xaml `ScrollViewer`. Let say you have a Image at the bottom of the ScrollViewer, which half area of the image is visible, and a bottom half are are outside of the screen (which means you need to "scroll down" the ScrollViewer). Seems like `Clip` only clips a area which is visible at the time, and when you scroll down the ScrollView, the half bottom of the image is cut down.

clip

And the revert issue is that...it can't be reset event when you set `nullptr` to `Clip`

```c++
uielement::Clip = clipRect; // clip area
...
uielement::Clip = nullptr; // Hope it "resets" clip area, but nothing changes
```

**Comment by sgtcoolguy** [comment]
@infosia I'm not surprised setting the Clip to nullptr doesn't work. I think to "revert" we basically need to set a rectangle that is the size of the original item we were clipping (or maybe even cheat and use 0,0 and some huge x/y numbers).

For the ScrollViewer, I don't know the answer, but it appears to be a pretty common Windows UI issue: 
- http://stackoverflow.com/questions/4856225/wpf-clipping-even-when-no-clipping-is-desired-how-to-turn-it-off
- http://blogs.msdn.com/b/ryanvog/archive/2009/01/20/clipping-legacy-content-hosted-inside-a-wpf-scrolling-region.aspx
- http://www.stackoverflow.dluat.com/questions/14050579/wp7-scrollviewer-content-clipped
- http://blog.anthonybaker.me/2013/05/wp8-tip-using-manipulation-events-to.html

Looks like maybe one solution is to hack the Clip by manipulating it when we receive some scroll events. Perhaps another is to place the ScrollViewer inside a Canvas and clip the canvas instead?

**Comment by infosia** [comment]
@sgtcoolguy ok sounds right. I think I need more experiment with it. I hope I can workaround it by handling scroll events in this case.

**Comment by infosia** [comment]
I was able to fix [TIMOB-19409](https://jira.appcelerator.org/browse/TIMOB-19409). Ready for merge.

```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'blue' });

var scrollView = Ti.UI.createScrollView({
    showVerticalScrollIndicator: true,
    showHorizontalScrollIndicator: true,
    height: '100%',
    width: '100%',
    contentHeight: 1000
});

var view1 = Ti.UI.createView({
    backgroundColor: 'red',
    width: 185, height: 185,
    top: 100
});
var imageview1 = Ti.UI.createImageView({
    image: 'http://image.tmdb.org/t/p/w780//3FweBee0xZoY77uO1bhUOlQorNH.jpg',
    top: -20, left: -185,
    width: 555, height: 312
});
view1.add(imageview1);

var view2 = Ti.UI.createView({
    backgroundColor: 'red',
    width: 185, height: 185,
    top: 550
});
var imageview2 = Ti.UI.createImageView({
    image: 'http://image.tmdb.org/t/p/w780//3FweBee0xZoY77uO1bhUOlQorNH.jpg',
    top: -20, left: -185,
    width: 555, height: 312
});
view2.add(imageview2);

scrollView.add(view1);
scrollView.add(view2);

win.add(scrollView);
win.open();
```

**Pull request merged**
