### PR TITLE
[TIMOB-23262] Fix: Ti.Media.showCamera() doesn't launch in full screen

### PR DESCRIPTION
**Pull request by infosia**
Fix [TIMOB-23262](https://jira.appcelerator.org/browse/TIMOB-23262)

- Camera preview should launch in full screen
- Camera preview should be placed at the bottom of the screen z order to accept overlaying view

```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green', layout: 'vertical' });

var overlay = Ti.UI.createView({ backgroundColor: 'blue', layout: 'vertical', height:'20%', width:Ti.UI.FILL }),
    takeButton = Ti.UI.createButton({ title: 'TAKE A PHOTO', backgroundColor: 'red' }),
    hideButton = Ti.UI.createButton({ title:'HIDE PREVIEW' , backgroundColor:'red'});

takeButton.addEventListener('click', function () {
    Ti.Media.takePicture();
});
hideButton.addEventListener('click', function () {
    Ti.Media.hideCamera();
});
overlay.add(takeButton);
overlay.add(hideButton);

win.addEventListener('open', function () {
    Ti.Media.showCamera({
        mediaTypes: [Ti.Media.MEDIA_TYPE_PHOTO],
    });
});

win.add(overlay);
win.open();
```

Note that in order to `showCamera` work, you need to set `webcam` capability, and also `takePicture` requires `videosLibrary` capability. 

```xml
  <windows>
    <manifest>
    <Capabilities>
      <Capability Name="internetClient" />
      <!-- Capability Name="videosLibrary" / -->
      <Capability Name="picturesLibrary" / >
      <DeviceCapability Name="webcam" />
    </Capabilities>
    </manifest>
  </windows>
```

### CODE REVIEW

**Comment by infosia** [comment]
build win 10

**Comment by sgtcoolguy** [comment]
*CR* looks good.

**Comment by sgtcoolguy** [comment]
@infosia Why would taking a picture require "videosLibrary" and not "picturesLibrary"?

**Comment by sgtcoolguy** [comment]
@infosia Using your code sample, I'm always getting an "Access is denied" failure in Ti.Media.showCamera. I think it's because the call happens off the main UI thread so I never even get prompted for permissions on the emulator. I think we need to wrap the camera code to ensure it's always run on the UI thread. This applies to the whole mdoule, not just this method...

**Comment by sgtcoolguy** [comment]
Looks like we're always saving to KnownFolders::VideoLibrary for all types. We probably should be saving to PicturesLibrary for some, CameraRoll for others and VideosLibrary for video.

**Comment by sgtcoolguy** [comment]
Finally figured out my issue for the access denied. Wasn't a threading issue, but a capabilities issue. With the default settings, you need the microphone capability as well for the camera! http://answers.flyppdevportal.com/MVC/Post/Thread/bcdc094a-6993-457d-82a7-478499a9848c?category=wpdevelop
I'd suggest we change that. We shouldn't require people to turn on these other capapbilities unnecessarily (like say microphone and videosLibrary for taking photos).

**Comment by sgtcoolguy** [comment]
According to the docs, the overlay is a property you can pass into the showCamera function. @infosia your example actually sets a view on the main window as the "overlay" that goes on top of the camera preview by virtue of z-ordering. I don't think this is correct. The new camera window should be full-screen, and should show system camera controls by default. How you do overlays/hide default controls are by properties to the function.

Looking at our docs, we should accept a number of options in this method. Specifically for the use case where you'd want a custom overlay that didn't obscure the preview, it appears we should support an `overlay` and `transform` property so you can specify the overlay view and how to scale/move the preview to fit under/next to the overlay.

See http://docs.appcelerator.com/platform/latest/#!/api/CameraOptionsType

**Comment by garymathews** [comment]
I don't seem to get the button overlay and the camera preview has the wrong orientation (landscape when I'm holding the phone in portrait)

**Comment by infosia** [comment]
ok, figured out rotation for `CaptureElement` needs some magic here:

```c++
GUID RotationKey = { 0xC380465D, 0x2271, 0x428C,{ 0x9B, 0x83, 0xEC, 0xEA, 0x3B, 0x4A, 0x85, 0xC1 } };

auto props = _mediaCapture->VideoDeviceController->GetMediaStreamProperties(Capture::MediaStreamType::VideoPreview);
props->Properties->Insert(RotationKey, rotationDegrees);
_mediaCapture->SetEncodingPropertiesAsync(Capture::MediaStreamType::VideoPreview, props, nullptr);
```

awful :(

[Capture photos and video with MediaCapture](https://msdn.microsoft.com/en-us/windows/uwp/audio-video-camera/capture-photos-and-video-with-mediacapture)

**Comment by infosia** [comment]
ok, should be working now.

```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green' }),
    openButton = Ti.UI.createButton({ title:'OPEN CAMERA', backgroundColor:'blue' });

var overlay = Ti.UI.createView({
    layout: 'vertical',
    height: '20%', width: Ti.UI.FILL,
    bottom: 0
}),
takeButton = Ti.UI.createButton({ title: 'TAKE A PHOTO', backgroundColor: 'red' }),
hideButton = Ti.UI.createButton({ title: 'HIDE PREVIEW', backgroundColor: 'red' });

takeButton.addEventListener('click', function () {
    Ti.Media.takePicture();
});
hideButton.addEventListener('click', function () {
    Ti.Media.hideCamera();
});
overlay.add(takeButton);
overlay.add(hideButton);

openButton.addEventListener('click', function () {
    Ti.Media.showCamera({
        mediaTypes: [Ti.Media.MEDIA_TYPE_PHOTO],
        overlay: overlay,
        success: function (e) {
            Ti.API.info('showCamera() success');
        },
        error: function () {
            Ti.API.info('showCamera() error');
        }
    });
});

win.add(openButton);
win.open();
```

**Comment by infosia** [comment]
build win 10

**Comment by infosia** [comment]
build win 10

**Comment by garymathews** [comment]
I've tested it again, the overlay works now, but it's still the wrong orientation. Although, I'm upside-down, I think it needs flipping vertically? I'm using a Nokia 909

**Comment by infosia** [comment]
@garymathews Is preview upside-down? What if you take a shot then? Is it upside-down too?

**Comment by garymathews** [comment]
@infosia, both the preview and the photo taken is upside-down

**Comment by infosia** [comment]
> I've tested it again, the overlay works now, but it's still the wrong orientation. I'm upside-down, I think it needs flipping vertically? I'm using a Nokia 909.

grr...it didn't happen on my Lumia 630 as well as my Windows 10 Mobile phone [KATANA 01](https://www.freetel.jp/lp/katana_spec/)...

> Also, when I rotate the phone into landscape the preview keeps its orientation. Should it rotate with the phone?

Added support for `autorotate` and `autohide`. Now it should rotate with the phone. Note that `autohide` is defaulting to `true` according to [docs](http://docs.appcelerator.com/platform/latest/#!/api/CameraOptionsType), so camera preview should be closed after `takePicture` by default.

**Comment by infosia** [comment]
Hmm, I've never seen this before...

```
```

**Comment by infosia** [comment]
build win 10

**Comment by infosia** [comment]
Shall we merge this for now so QE can test this easily?

**Comment by garymathews** [comment]
build win 10

**Comment by infosia** [comment]
build win 10

**Comment by infosia** [comment]
Seems like timeout occurs during `donwloadLargeFile`. Network is unstable?

**Comment by infosia** [comment]
build win 10

**Comment by garymathews** [comment]
build win 10

**Pull request merged**
