### PR TITLE
[TIMOB-23427] Default camera control for Windows 10 apps

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-23427](https://jira.appcelerator.org/browse/TIMOB-23427)

Show default camera UI when no `overlay` is specified. Note that _default camera UI won't be available for Windows Phone 8.1_.

```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green', layout: 'vertical' }),
    openButton = Ti.UI.createButton({ title: 'OPEN CAMERA', backgroundColor: 'blue' }),
    imageView = Ti.UI.createImageView({ width: Ti.UI.FILL, height: '80%' });

openButton.addEventListener('click', function () {
    Ti.Media.showCamera({
        mediaTypes: [Ti.Media.MEDIA_TYPE_PHOTO],
        success: function (e) {
            Ti.API.info('showCamera() success');
            imageView.image = e.media;
        },
        error: function (e) {
            alert('showCamera() error: ' + JSON.stringify(e));
        }
    });
});

win.add(openButton);
win.add(imageView);
win.open();
```

Default camera UI for Windows 10 Mobile (See [Windows Camera](https://www.microsoft.com/en-us/store/apps/windows-camera/9wzdncrfjbbg))
windowscamera

### CODE REVIEW

**Comment by garymathews** [comment]
CR: **PASS**
FR: **PASS**

**Comment by garymathews** [comment]
test this please

**Comment by infosia** [comment]
build win 10

**Comment by infosia** [comment]
###  Jenkins TitaniumKit PR Build

I don't know what's going on there....

```
12:46:44          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\atomic(735): fatal error C1083: Cannot open include file: 'xxatomic': No such file or directory [C:\Jenkins\workspace\TitaniumKit-prs\build\testing
```

**Comment by infosia** [comment]
build win 10

**Pull request merged**
