### PR TITLE
[TIMOB-24975][TIMOB-25038] SearchBar fixes

### PR DESCRIPTION
**Pull request by infosia**
* [TIMOB-24975](https://jira.appcelerator.org/browse/TIMOB-24975) SearchBar should show "No Results' text
* [TIMOB-25038](https://jira.appcelerator.org/browse/TIMOB-25038) SearchBar cancel button should be hidden on its click

SearchBar + TableView

```js
var _window = Ti.UI.createWindow({ backgroundColor: 'green' });
var searchBar = Ti.UI.createSearchBar({
    showCancel: true
});
var data = [];

for (var i = 0; i < 25; i++) {
    data.push({ title: `Row ${i}` });
}
var tableView = Ti.UI.createTableView({
    search: searchBar,
    data: data
});
_window.add(tableView);
_window.open();
```

SearchBar + ListView

```js
var _window = Ti.UI.createWindow({ backgroundColor: 'green' });
var searchBar = Ti.UI.createSearchBar({
    showCancel: true
});
var data = [];

for (var i = 0; i < 25; i++) {
    data.push({ properties: { title: `Row ${i}` } });
}

var section = Ti.UI.createListSection();
section.setItems(data);

var listView = Ti.UI.createListView({
    searchView: searchBar,
    sections: [section]
});
_window.add(listView);
_window.open();
```

### CODE REVIEW

**Comment by infosia** [comment]
Makes sense, added [TIMOB-25331](https://jira.appcelerator.org/browse/TIMOB-25331) to track it.

**Comment by ssjsamir** [comment]
@infosia  The issues seen in https://jira.appcelerator.org/browse/TIMOB-25038 still exists on windows 10 mobile device [Lumia 550 (10.0.14393.0)] but on ws-local it is fine

**Comment by infosia** [comment]
@ssjsamir Hmm, for me it woks well on Windows 10 Mobile device (10.0.14393.0). The 'X' button disappears when I removed all tests, as well as after pressing 'X'. I would merge this PR for now and keep `TIMOB-25038` open (with removing `7.0.0` label) because we have such short time frame for 7.0.0?

**Comment by mukherjee2** [comment]
Merging. Ticket will be validated post merge.

**Comment by mukherjee2** [comment]
@infosia I think we can close TIMOB-25038 as well. When I clicked the "X", it disappears. I am using Windows 10 Mobile device 10.0.15063. What do you think? I was able to validate everything in this PR.

**Comment by infosia** [comment]
@mukherjee2 ok sounds good to me 👍

**Pull request merged**
