### PR TITLE
[TIMOB-20286] Expose Ti.UI.View.getViewById method

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-20286](https://jira.appcelerator.org/browse/TIMOB-20286)

Expose `Ti.UI.View.getViewById` to find a child view by its `id`
Basically based on a logic done in https://github.com/appcelerator/titanium_mobile/pull/8677

```js
var win = Ti.UI.createWindow({
    backgroundColor: '#fff'
});

var container = Ti.UI.createView({
    width: 300,
    height: 300,
    backgroundColor: 'red'
});

var btn = Ti.UI.createButton({
    title: 'Get view by ID',
    id: 'myButton'
});

btn.addEventListener('click', function () {
    var myButton = win.getViewById('myButton');

    // If no button is found, it will return null
    if (myButton) {
        myButton.setTitle('Worked! ');
    }
});

container.add(btn);
win.add(container);
win.open();
```

### CODE REVIEW

**Comment by garymathews** [comment]
[Update documentation](https://github.com/appcelerator/titanium_mobile/pull/8677/files#diff-0cc7dd4ed3fbabcc1ea4d811f65da9dc)

**Comment by garymathews** [comment]
CR: **PASS**
FT: **PASS**

👍

**Comment by hansemannn** [comment]
Thanks Kota! just resolved with latest master, we can merge now. But I'd wait until @garymathews merges https://github.com/appcelerator/titanium_mobile/pull/8677, so you can add the windows-specific docs. If I understood it correctly, they then get merged together for the web-docs?

**Comment by infosia** [comment]
test this please

**Comment by infosia** [comment]
test this please

**Comment by infosia** [comment]
build win 10

**Comment by infosia** [comment]
Should be ok to merge for now.

**Pull request merged**
