### PR TITLE
Force "en" instead of "en-US" for the default language

### PR DESCRIPTION
**Pull request by infosia**
Force "en" instead of "en-US" for the default language.

```
> appc ti build -p windows --build-only
[WARN]  MakePRI : warning 0xdef00522: no resources found for default language(s): 'en-US'.
Change the default language or qualify resources with the default language.
http://go.microsoft.com/fwlink/?LinkId=231899
```

Introduced by #737.

### CODE REVIEW

**Comment by infosia** [comment]
build win 10

**Comment by garymathews** [comment]
build win 10

**Comment by garymathews** [comment]
build win 10

**Comment by garymathews** [comment]
FR: **PASS**
CR: **PASS**

**Pull request merged**
