### PR TITLE
[TIMOB-18940] Implement the ability to use native modules with a titanium project

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-18940](https://jira.appcelerator.org/browse/TIMOB-18940)

-  Add native module support for Titanium CLI
- Add native module DLL/winmd finder for CMake based on `tiapp.xml`.

Native module `manifest` should look like below. module's `projectname` will be used for generating cmake module project name. `classname` entry should be module's C++ class name. In this case module directory should have `ComExampleTest2.DLL` and `ComExampleTest2.winmd` under modulePath + `${PLATFORM}/${Ti_ARCH}` directory.

```
#
# this is your module manifest and used by Titanium
# during compilation, packaging, distribution, etc.
#
version: 0.1
apiversion: 2
description: Example module 2
author: Ping Wang
license: Apache Public License v2
copyright: Copyright (c) 2009-2015 by Appcelerator, Inc.

# these should not be edited
name: com.example.test2
moduleid: com.example.test2
guid: e4f7ac61-1ee7-44c5-bc27-fa6876e2dce8
platform: windows
classname: Com::Example::Test2
projectname: ComExampleTest2
```

### CODE REVIEW

**Comment by infosia** [comment]
Here's a sample module to test if this works [com.example.test1.zip](https://www.dropbox.com/s/b0ypepfi7lcx84s/com.example.test1.zip?dl=0). To install this unzip it then copy `com.example.test1` folder into your `YOUR_TITANIUM_SDK/modules/windows` folder.

Sample code:
```
var test = require('com.example.test1');
Ti.API.info(test.hello());
```

Note that you also need `module` entry in your `tiapp.xml`.

```
	<modules>
		<module platform="windows">com.example.test1</module>
	</modules>
```

**Comment by sgtcoolguy** [comment]
@infosia in testing this, it looks to me like we're getting bad paths to the native modules. Specifically, it's using: C:/ProgramData/Application Data/Titanium/modules/windows/com.example.test1/0.1

When the module is actually at C:\ProgramData\Titanium\modules\windows\com.example.test1\0.1

Obviously this results in a broken build.

It looks to me like this is a bug up in the Titanium CLI itself, not our hook.

**Comment by sgtcoolguy** [comment]
Hmm, nevermind, this is a red herring. That path is valid and is just a link to the other one.

Looking deeper. Looks like there's double quotes around the path it searches for the winmd file. Not sure why it has double quotes in the CLI output, but not in the cmake file...

**Comment by sgtcoolguy** [comment]
```
[INFO]  ResolveAssemblyReferences:
         Primary reference "ComExampleTest1".
[INFO]  5>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersio
n.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not
locate the assembly "ComExampleTest1". Check to make sure the assembly exists on
 disk. If this reference is required by your code, you may get compilation error
s. [C:\Users\Christopher\AppData\Local\Temp\mocha\wp.x86\Native\TitaniumWindows_
Native.vcxproj]
                 For SearchPath "C:\Program Files (x86)\Microsoft Visual Studio
12.0\VC\atlmfc\lib".
                 Considered "C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\atlmfc\lib\ComExampleTest1.winmd", but it didn't exist.
                 Considered "C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\atlmfc\lib\ComExampleTest1.dll", but it didn't exist.
                 Considered "C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\atlmfc\lib\ComExampleTest1.exe", but it didn't exist.
                 For SearchPath "C:\Program Files (x86)\Microsoft Visual Studio
12.0\VC\lib".
                 Considered "C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\lib\ComExampleTest1.winmd", but it didn't exist.
                 Considered "C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\lib\ComExampleTest1.dll", but it didn't exist.
                 Considered "C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\lib\ComExampleTest1.exe", but it didn't exist.
                 For SearchPath "{HintPathFromItem}".
                 Considered ""C:\ProgramData\Application Data\Titanium\modules\w
indows\com.example.test1\0.1\phone\x86\ComExampleTest1.winmd"", but it didn't ex
ist.
                 For SearchPath "{TargetFrameworkDirectory}".
                 Considered "C:\Program Files (x86)\Windows Phone Kits\8.1\\Refe
rences\CommonConfiguration\Neutral\ComExampleTest1.winmd", but it didn't exist.
                 Considered "C:\Program Files (x86)\Windows Phone Kits\8.1\\Refe
rences\CommonConfiguration\Neutral\ComExampleTest1.dll", but it didn't exist.
                 Considered "C:\Program Files (x86)\Windows Phone Kits\8.1\\Refe
rences\CommonConfiguration\Neutral\ComExampleTest1.exe", but it didn't exist.
                 For SearchPath "{GAC}".
                 Considered "ComExampleTest1", which was not found in the GAC.
                 For SearchPath "{RawFileName}".
                 Considered treating "ComExampleTest1" as a file name, but it di
dn't exist.
                 For SearchPath "C:\Users\Christopher\AppData\Local\Temp\mocha\w
p.x86\Native\Release\".
                 Considered "C:\Users\Christopher\AppData\Local\Temp\mocha\wp.x8
6\Native\Release\ComExampleTest1.winmd", but it didn't exist.
                 Considered "C:\Users\Christopher\AppData\Local\Temp\mocha\wp.x8
6\Native\Release\ComExampleTest1.dll", but it didn't exist.
                 Considered "C:\Users\Christopher\AppData\Local\Temp\mocha\wp.x8
6\Native\Release\ComExampleTest1.exe", but it didn't exist.
```

**Comment by infosia** [comment]
@sgtcoolguy Can you paste whole contents of `C:\Users\Christopher\AppData\Local\Temp\mocha\wp.x86\Native\CMakeLists.txt`? I suspect something wrong during module path generation.

**Comment by sgtcoolguy** [comment]
@infosia I finally narrowed it down. We should not only be changing \ to / in paths, but also escaping spaces with a preceding slash. But there's also a bug in CMake where it ends up using a quoted path in the vcxproj's HintPath xml item if the path has any spaces. Since it's pure text content of a tag, the quotes are unnecessary/wrong. So for now I'm hacking the vcxproj contents after we run cmake to remove the unnecessary quotes. We should file a bug with ms cmake to let them know (though it looks like they've moved on full speed ahead into Windows 10 work).

**Comment by sgtcoolguy** [comment]
Opened Microsoft/Cmake#4

**Pull request merged**
