### PR TITLE
[TIMOB-23678] Fix Ti.Network.HTTPClient.send() concurrency

### PR DESCRIPTION
**Pull request by garymathews**
- Fixed ``RequestState`` enum order
- ``Titanium.Network.HTTPClient.send()`` is now fully asynchronous

###### TEST CASE
```Javascript
var win = Ti.UI.createWindow(),
    btn = Ti.UI.createButton({
        title: 'HTTP GET'
    });

btn.addEventListener('click', function () {
    var request = Ti.Network.createHTTPClient({
            onload: function () {
                alert('onload:\n\treadyState: ' + request.readyState);
            },
            onerror: function (e) {
                alert('onerror:\n\treadyState: ' + request.readyState + '\n\terror: ' + e.error);
            }
        }),
        timeout = new Date().getTime() + 5000,
        host = 'http://www.google.com/',
        done = false;

    request.cache = false;
    request.open('GET', host);
    request.send();

    while (!done) {
        if (request.readyState === 4 || request.status === 404) {
            done = true;
            alert('success');
        } else if ((timeout - (new Date()).getTime()) <= 0) {
            done = true;
            alert('failed');
        }
    }
});

win.add(btn);
win.open();
```
```
onload:
    readyState: 4
```
```
success
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23678)

### CODE REVIEW

**Comment by infosia** [comment]
ok, looks good to me 👍

**Comment by garymathews** [comment]
test this please

**Comment by infosia** [comment]
test this please

**Comment by garymathews** [comment]
test this please

**Comment by infosia** [comment]
I'm not quite convinced why Jenkins keeps failing including even on Win 8.1. Looking into this.

**Comment by infosia** [comment]
I got this during `ti.network.httpclient.test.js`. Exception thrown in `HTTPClient::onload`.

```
Exception thrown at 0x777BE26B (KernelBase.dll) in NMocha.exe: 0x40080201: WinRT originate error (parameters: 0x8001010E, 0x00000051, 0x04DFC7E0).
Exception thrown at 0x777BE26B in NMocha.exe: Microsoft C++ exception: Platform::WrongThreadException ^ at memory location 0x04DFCCC8. HRESULT:0x8001010E The application called an interface that was marshalled for a different thread.
WinRT information: The application called an interface that was marshalled for a different thread.

HAL 000000000 Tue Aug  2 09:46:05 2016 ERROR: JSExportClass<class Titanium::GlobalObject>::CallNamedFunction: unknown exception.
Exception thrown at 0x777BE26B in NMocha.exe: Microsoft C++ exception: HAL::detail::js_runtime_error at memory location 0x04DFECE8.
[WARN] Error during HttpClient:onload
The thread 0x1130 has exited with code 0 (0x0).
```

**Comment by infosia** [comment]
test this please

**Comment by garymathews** [comment]
I need to figure out why a test case produces `The application called an interface that was marshalled for a different thread.`

That usually means a UI task is not running on the UI thread.

**Comment by garymathews** [comment]
Updated PR, should pass tests now

**Comment by garymathews** [comment]
build win 10

**Comment by infosia** [comment]
I hit intermittent crash on Win 10 with this PR like we saw in Jenkins build. Looking into this...

**Comment by infosia** [comment]
As far as I can see, interestingly`use_arbitrary()` soars the application memory, which leads the crash.

concurrent

After moving `use_arbitrary()` to `use_current()`, memory issue is fixed. I'm not quite sure why but we want to avoid `use_arbitrary()` for now?

master

**Comment by garymathews** [comment]
But then LiveView won't work and cases such as:

```Javascript
request.send();
while (!done) {
    if (request.readyState === 4 || request.status === 404) {
        done = true;
        alert('success');
    }
}
```

We need `send()` to be asynchronous. I'm confused as to why this is happening, is there a memory leak of some sort?

**Comment by infosia** [comment]
> We need send() to be asynchronous. I'm confused as to why this is happening, is there a memory leak of some sort?

Ahh I see 😞  I saw soaring memory had freed all at once, so I suspect that blocking arbitrary thread dams something (JavaScript GC etc), but I'm not sure. I'll look into it.

**Comment by garymathews** [comment]
I find it interesting how this issue only affects Windows 10

**Comment by infosia** [comment]
And looks like it happens only on Win 10 Store app.

**Comment by garymathews** [comment]
So I've been investigating, and I have found something interesting. If you remove ANY test case from `ti.network.httpclient.test.js` the test cases from Windows 10 Desktop will pass.

**Comment by infosia** [comment]
Merged by #810

**Pull request closed without merging**
