### PR TITLE
Fix: Ti.UI.View.insertAt and replaceAt not working

### PR DESCRIPTION
**Pull request by infosia**
Fix for [TIMOB-19355](https://jira.appcelerator.org/browse/TIMOB-19355).

```javascript
var win = Ti.UI.createWindow({backgroundColor:'black'});


var view1 = Ti.UI.createView({
    backgroundColor: 'blue',
    top: 0, left: 0,
    width: 100, height: 100
});
var view2 = Ti.UI.createView({
    backgroundColor: 'yellow',
    top: 30, left: 30,
    width: 100, height: 100
});
var view3 = Ti.UI.createView({
    backgroundColor: 'red',
    top: 60, left: 60,
    width: 100, height: 100
});

win.add(view1);
win.add(view2);
win.add(view3);

var commandBar = Ti.UI.createView({
    backgroundColor: 'green',
    width: Ti.UI.FILL, height: '10%',
    bottom: 0, left: 0,
    layout:'horizontal'
});

var view1Top = Ti.UI.createButton({ title: ' insert ',   width: '30%'});
var view2Top = Ti.UI.createButton({ title: ' replace ', width: '30%' });
var view3Top = Ti.UI.createButton({ title: ' replace ', width: '30%' });

view1Top.addEventListener('click', function () {
    var newview = Ti.UI.createView({
        backgroundColor: 'green',
        top: 100, left: 100,
        width: 100, height: 100
    });
    win.insertAt({ view: newview, position: 2 });
});
view2Top.addEventListener('click', function () {
    var newview = Ti.UI.createView({
        backgroundColor: 'gray',
        top: 100, left: 100,
        width: 100, height: 100
    });
    win.replaceAt({ view: newview, position: 2 });
});
view3Top.addEventListener('click', function () {
    var newview = Ti.UI.createView({
        backgroundColor: 'magenta',
        top: 0, left: 0,
        width: 120, height: 120
    });
    // this should replace blue view
    win.replaceAt({ view: newview, position: 0 });
});

commandBar.add(view1Top);
commandBar.add(view2Top);
commandBar.add(view3Top);

win.add(commandBar);
win.open();
```

### CODE REVIEW

**Comment by yuchi** [comment]
:tada: /cc @FokkeZB

**Comment by infosia** [comment]
Turns out that based on what I saw in [Android implementation](https://github.com/appcelerator/titanium_mobile/blob/master/android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java#L601), `insertAt/replaceAt` is meant to be used for `vertical` and `horizontal` layout, to replace/insert view element at specific position, right? I wasn't aware of that, my implementation is not enough...

**Comment by FokkeZB** [comment]
@infosia well, the comments there say it's most useful for those cases but it should work for composite layouts as well.

**Comment by infosia** [comment]
@FokkeZB What will happen when it is used for composite layout? Something will be changed visually?

**Comment by infosia** [comment]
I mean, something like view order or z-order or something related to Titanium layout system.

**Comment by FokkeZB** [comment]
That's what it should do but I see on iOS it's not working well with composite:

```
var win = Ti.UI.createWindow({backgroundColor:'white'});
win.add(Ti.UI.createView({backgroundColor:'red',width:200,height:200}));
win.add(Ti.UI.createView({backgroundColor:'blue',width:100,height:100}));
win.insertAt({view:Ti.UI.createView({backgroundColor:'green',width:50,height:50}),position:1});
alert(win.children.length);
win.open();
```

img_9192

**Comment by FokkeZB** [comment]
Sorry for that (now deleted) comment. It works fine on iOS with composite layouts. It will stack the views in the expected z-order. I expect it works the same on Android (but will check) and should on Windows as well.

**Comment by yuchi** [comment]
In composite layouts the order of children specifies the order on the z stack when `zIndex` is unspecified. As per docs, and inherited by the box model, all children without a specified `zIndex`

**Comment by yuchi** [comment]
(Continues) are placed behind the views with a specified `zIndex`, and between them they are placed from the bottom to the top.

**Comment by infosia** [comment]
@yuchi @FokkeZB Thanks for following up :+1:

**Comment by infosia** [comment]
Pushed the changes to make it work with Titanium layout:

Sample code:
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'black', layout:'vertical' });

var view1 = Ti.UI.createView({
    backgroundColor: 'blue',
    height: '10%'
});
var view2 = Ti.UI.createView({
    backgroundColor: 'yellow',
    height: '10%'
});
var view3 = Ti.UI.createView({
    backgroundColor: 'red',
    height: '10%'
});

win.add(view1);
win.add(view2);
win.add(view3);

var commandBar = Ti.UI.createView({
    backgroundColor: 'black',
    width: Ti.UI.FILL, height: '10%',
    bottom: 0, left: 0,
    layout: 'horizontal'
});

var view1Top = Ti.UI.createButton({ title: ' insert ', width: '30%' });
var view2Top = Ti.UI.createButton({ title: ' replace ', width: '30%' });
var view3Top = Ti.UI.createButton({ title: ' replace ', width: '30%' });

view1Top.addEventListener('click', function () {
    var newview = Ti.UI.createView({
        backgroundColor: 'green',
        height: '10%'
    });
    win.insertAt({ view: newview, position: 1 });
});
view2Top.addEventListener('click', function () {
    var newview = Ti.UI.createView({
        backgroundColor: 'gray',
        height: '10%'
    });
    // this should replace second view
    win.replaceAt({ view: newview, position: 1 });
});
view3Top.addEventListener('click', function () {
    var newview = Ti.UI.createView({
        backgroundColor: 'magenta',
        height: '10%'
    });
    // this should replace first view
    win.replaceAt({ view: newview, position: 0 });
});

commandBar.add(view1Top);
commandBar.add(view2Top);
commandBar.add(view3Top);

win.add(commandBar);
win.open();
```

zIndex support will be done by https://github.com/appcelerator/titanium_mobile_windows/pull/404

**Pull request merged**
