### PR TITLE
[TIMOB-25760] [TIMOB-25789] Parity around HttpClient redirection and events

### PR DESCRIPTION
**Pull request by infosia**
[TIMOB-25789](https://jira.appcelerator.org/browse/TIMOB-25789) and [TIMOB-25760](https://jira.appcelerator.org/browse/TIMOB-25760)

HttpClient `callbackTestForGETMethod` and `callbackTestForPOSTMethod` [unit test](https://github.com/appcelerator/titanium-mobile-mocha-suite/blob/master/Resources/ti.network.httpclient.test.js#L377) shows `onreadystatechange` should be called right after `ondatastream/onsendstream` to keep parity with iOS/Android.

```js
var win = Ti.UI.createWindow({
    backgroundColor: 'white'
});

win.addEventListener('open', function () {
    var xhr = Ti.Network.createHTTPClient(),
    attempts = 3,
    sendStreamFinished = false,
    buffer;
    xhr.setTimeout(3e4);

    xhr.onreadystatechange = function () {
        Ti.API.info('onreadystatechange sendStreamFinished: ' + sendStreamFinished + ' DONE? ' + (this.readyState === this.DONE));
        if (this.readyState === this.DONE && sendStreamFinished) {
            Ti.API.info('finish');
        }
    };
    xhr.onsendstream = function (e) {
        Ti.API.info('onsendstream');
        Ti.API.info(e.progress + ' be.ok');
        if (e.progress >= 0.99) {
            sendStreamFinished = true;
        }
    };
    xhr.onerror = function (e) {
        if (attempts-- > 0) {
            Ti.API.warn('failed, attempting to retry request...');
            xhr.send();
        } else {
            Ti.API.warn(JSON.stringify(e, null, 2));
            Ti.API.warn(e.error || this.responseText);
        }
    };
    buffer = Ti.createBuffer({
        length: 1024 * 10
    }).toBlob();
    xhr.open('POST', 'http://www.httpbin.org/post');
    xhr.send({
        data: buffer,
        username: 'fgsandford1000',
        password: 'sanford1000',
        message: 'check me out'
    });
});

win.open();
```

Expected: `finish` should be printed.

Test for [TIMOB-25760](https://jira.appcelerator.org/browse/TIMOB-25760)

```js
var _tmpURL = "https://goo.gl/TckK14"
var _tmpClient = Ti.Network.createHTTPClient({
    onload: function (e) {
        serverAddressRedirected = _tmpClient.location;
        //this should return redirected url
        alert("Location:" + serverAddressRedirected);
    },
    onerror: function (e) {
        alert("Error:" + e.error);
    },
    timeout: 30000
});
_tmpClient.open("GET", _tmpURL);
_tmpClient.send();
```

Expected: `Location: https://translate.google.com/#auto/bn/` should be shown.

Also make sure liveview works as expected.

### CODE REVIEW

**Comment by garymathews** [comment]
We should test this change with LiveView

**Comment by infosia** [comment]
Hmm right. This broke liveview. Same issue with #1182.

**Comment by infosia** [comment]
Liveview should be working now.

**Comment by infosia** [comment]
@ssjsamir Fixed. Thanks for heads up 👍

**Comment by infosia** [comment]
Seems like this makes LiveView  unstable. Let me check.

**Comment by infosia** [comment]
Closing this, revised by #1318

**Pull request closed without merging**
